import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { readFile, writeFile } from "node:fs/promises";
import Ajv from "ajv";
import standaloneCode from "ajv/dist/standalone/index.js";
import {
  CAMERA_DOCUMENT_SCHEMA,
  CAMERA_VALUE_SCHEMAS,
} from "../src/config/camera/fields";
const ajv = new Ajv({
  strict: true,
  allErrors: true,
  code: { source: true, esm: true },
  inlineRefs: false,
});
ajv.addSchema(CAMERA_DOCUMENT_SCHEMA, "document");
for (const [kind, schema] of Object.entries(CAMERA_VALUE_SCHEMAS))
  ajv.addSchema(schema, kind);
const output = standaloneCode(ajv, {
  validateCameraDocument: "document",
  validateThirdPerson: "third-person",
  validateFirstPerson: "first-person",
  validateShoulder: "shoulder",
  validateThirdPersonOverride: "document#/$defs/third-person",
  validateFirstPersonOverride: "document#/$defs/first-person",
  validateShoulderOverride: "document#/$defs/shoulder",
});
const bundled = await build({
  absWorkingDir: fileURLToPath(new URL("..", import.meta.url)),
  stdin: {
    contents: output,
    resolveDir: fileURLToPath(new URL("..", import.meta.url)),
    sourcefile: "camera-validator-standalone.js",
  },
  bundle: true,
  write: false,
  format: "esm",
  platform: "browser",
  legalComments: "inline",
});
const require = createRequire(import.meta.url);
const license = await readFile(require.resolve("ajv/LICENSE"), "utf8");
await writeFile(
  new URL("../src/config/camera/validator.generated.ts", import.meta.url),
  "// @ts-nocheck\n// Generated by scripts/generate-camera-validator.ts with Ajv 8.17.1. Do not edit.\n" +
    "/*! Bundled Ajv runtime helper license:\n" +
    license +
    "*/\n" +
    bundled.outputFiles[0]!.text.trimEnd() +
    "\n",
);

// Derived discovery data. The browser source dependency graph is the authority;
// Creator reads only this JSON and verifies its complete local source closure.
const { CAMERA_FIELD_METADATA } = await import('../src/config/camera/fields');
const { createHash } = await import('node:crypto');
const path = await import('node:path');
const packageRoot = fileURLToPath(new URL('..', import.meta.url));
const graph = await build({absWorkingDir:packageRoot,entryPoints:['src/config/camera/index.ts'],bundle:true,write:false,metafile:true,packages:'external',platform:'browser',format:'esm'});
const sources:Record<string,string> = {};
for(const input of Object.keys(graph.metafile!.inputs).sort()) {
  const relative = path.relative(path.join(packageRoot,'src'),path.resolve(packageRoot,input)).split(path.sep).join('/');
  if(relative.startsWith('../') || !relative.endsWith('.ts')) throw new Error(`CAMERA_DISCOVERY_SOURCE_OUTSIDE_SDK: ${input}`);
  sources[relative] = createHash('sha256').update(await readFile(path.resolve(packageRoot,input))).digest('hex');
}
await writeFile(new URL('../src/config/camera/discovery.generated.json',import.meta.url),JSON.stringify({schemaVersion:1,entry:'config/camera/index.ts',sources,schema:CAMERA_DOCUMENT_SCHEMA,fields:CAMERA_FIELD_METADATA},null,2)+'\n');
