import { hashRootMotionSourceV1, type RootMotionSourceBodyV1 } from "@whitebox-world/character-movement";
import { hashActionPresentationBindingV1, type ActionPresentationBindingBodyV1 } from "@whitebox-world/subject-actions";
import type { RuntimeRigProfileV1, RuntimeSubjectCapabilityAssemblyV1, WorldRuntimeBootstrapBodyV1 } from "./world-runtime-bootstrap.js";

// Package-owned data fixture shared by Bootstrap contract tests only.
const HASH_A = `sha256:${"a".repeat(64)}` as const;
const HASH_B = `sha256:${"b".repeat(64)}` as const;
const GAMEPLAY_REF = "worldkit://gameplay-bootstrap/runtime-test@1";

const rootMotionBody = {
  schemaVersion: 1,
  resourceRef: "worldkit://root-motion/runtime-bootstrap-test@1",
  fixedDeltaSeconds: 1 / 60,
  samples: [{
    translationDeltaMetersXYZ: [0, 0, 0.1],
    facingYawDeltaRadians: 0,
  }],
} as const satisfies RootMotionSourceBodyV1;
const rootMotionSource = {
  ...rootMotionBody,
  contentHash: hashRootMotionSourceV1(rootMotionBody),
};
const actionBindingBody = {
  kind: "action-presentation-binding",
  schemaVersion: 1,
  resourceRef: "worldkit://action-presentation/runtime-bootstrap-test@1",
  presentationKey: "action.runtime-bootstrap-test",
  semanticActionRef: "worldkit://semantic-action/runtime-bootstrap-test@1",
  semanticActionHash: HASH_A,
  isInterruptible: true,
  clip: {
    sourceClipName: "RuntimeBootstrapTest",
    loopMode: "once",
    playbackSpeedRatio: 1,
    blendDurationTicks: 3,
  },
  rootMotion: {
    mode: "locked",
    rootMotionSourceRef: rootMotionSource.resourceRef,
    rootMotionSourceHash: rootMotionSource.contentHash,
    priority: 100,
  },
} as const satisfies ActionPresentationBindingBodyV1;
const actionBinding = {
  ...actionBindingBody,
  contentHash: hashActionPresentationBindingV1(actionBindingBody),
};

const cameraParameters = {
  distanceMeters: 5,
  minimumDistanceMeters: 2,
  maximumDistanceMeters: 8,
  targetHeightMeters: 1.4,
  shoulderOffsetMeters: 0.2,
  pitchRadians: 0.2,
  minimumPitchRadians: -0.8,
  maximumPitchRadians: 0.6,
  positionDampingPerSecond: 8,
  horizontalPositionDampingPerSecond: 8,
  verticalPositionDampingPerSecond: 8,
  maximumPositionLagMeters: 2,
  rotationDampingPerSecond: 8,
  yawDampingPerSecond: 8,
  pitchDampingPerSecond: 8,
  collisionRadiusMeters: 0.2,
  collisionRetractionMetersPerSecond: 20,
  collisionRecoveryMetersPerSecond: 8,
  baseFovDegrees: 60,
  speedFovDegreesPerMeterPerSecond: 0,
  maximumSpeedFovDegrees: 0,
  lookAheadSeconds: 0,
  accelerationLookAheadSecondsSquared: 0,
  transitionSeconds: 0.2,
  minimumHeadingSpeedMetersPerSecond: 0.1,
  velocityHeadingDampingPerSecond: 8,
  fovDampingPerSecond: 8,
  horizontalDeadZoneRatio: 0,
  verticalDeadZoneRatio: 0,
  recenterDelaySeconds: 0.5,
  recenterDurationSeconds: 0.3,
  recenterMinimumSpeedMetersPerSecond: 0.5,
  teleportSnapDistanceMeters: 10,
  lookSensitivityXRatio: 1,
  lookSensitivityYRatio: 1,
} as const;

function capabilityAssemblyFixture(): RuntimeSubjectCapabilityAssemblyV1 {
  const motionProfile = {
    resourceRef: "worldkit://motion-profile/runtime-test@1",
    contentHash: HASH_A,
    motionKernelRef: "worldkit://motion-kernel/runtime-test@1",
    motionTags: ["ground"],
  };
  return {
    authoringAvailability: "recommended",
    physicsBodyProfileRef: "worldkit://physics-body-profile/runtime-test@1",
    locomotionProfileRef: "worldkit://locomotion-profile/runtime-test@1",
    defaultMotionProfile: motionProfile,
    optionalMotionProfiles: [{ ...motionProfile, resourceRef: "worldkit://motion-profile/runtime-alt@1" }],
    fallbackMotionProfile: motionProfile,
    motionKernels: [{
      resourceRef: "worldkit://motion-kernel/runtime-test@1",
      implementationId: "free-ground",
      commandKind: "planar-vector",
      supportedMediums: ["ground", "air"],
      fallbackMotionProfileRef: motionProfile.resourceRef,
      deterministic: true,
    }],
    controlProfile: {
      resourceRef: "worldkit://control-profile/runtime-test@1",
      contentHash: HASH_A,
      commandKind: "planar-vector",
      inputSpace: "camera-relative",
      facingPolicy: "align-to-move",
      lateralMovementPolicy: "allowed",
      moveDeadzoneRatio: 0.1,
    },
    cameraContext: {
      resourceRef: "worldkit://camera-context/runtime-test@1",
      defaultCameraRigProfileRef: "worldkit://camera-profile/runtime-test@1",
      firstPersonCameraRigProfileRef: "worldkit://camera-profile/runtime-first-person@1",
      rules: [{
        id: "running",
        priority: 10,
        when: {
          allRelationshipConditions: [{
            type: "mountedOn",
            entityRole: "rider",
          }],
          locomotionStatuses: ["active"],
          mobilityModes: ["grounded"],
          gaits: ["run"],
          verticalPhases: ["none"],
          requiredActiveActionRefs: ["worldkit://semantic-action/run@1"],
          actionInterruptibility: "interruptible",
          movementMediums: ["ground"],
          minimumSpeedMetersPerSecond: 1,
          maximumSpeedMetersPerSecond: 8,
          requiredSocketIds: ["camera-target"],
          requiredCameraContextTags: ["follow"],
        },
        cameraRigProfileRef: "worldkit://camera-profile/runtime-test@1",
        cameraModifierRefs: ["worldkit://camera-modifier/runtime-test@1"],
      }],
      cameraRigProfiles: [{
        resourceRef: "worldkit://camera-profile/runtime-test@1",
        contentHash: HASH_A,
        baseMode: "stable-follow",
        algorithmRef: "worldkit://camera-rig/stable-follow@1",
        headingSource: "view",
        reverseHeadingPolicy: "preserve-target-forward",
        recenterMode: "forward-motion",
        preferredSocketIds: ["camera-target"],
        parameters: cameraParameters,
        authoringRanges: {
          distanceMeters: { minimum: 2, maximum: 8, step: 0.25 },
        },
      }],
      cameraModifierProfiles: [{
        resourceRef: "worldkit://camera-modifier/runtime-test@1",
        parameterOverrides: { distanceMeters: 6 },
        headingSourceOverride: "target-forward",
        reverseHeadingPolicyOverride: "follow-velocity",
        recenterModeOverride: "always",
      }],
    },
    mediumProfile: {
      resourceRef: "worldkit://medium-profile/runtime-test@1",
      air: { gravityRatio: 1, linearDragPerSecond: 0.1 },
    },
    relationshipProfiles: [{
      resourceRef: "worldkit://relationship-profile/mounted-on.stand-ground@1",
      relationshipType: "mountedOn",
      requiredRiderSocketIds: ["feet"],
      requiredMountSocketIds: ["deck"],
      controlTransferMode: "to-mount",
      cameraTargetRole: "mount",
      maximumMountDistanceMeters: 1,
    }],
    harnessProfileRef: "worldkit://harness-profile/runtime-test@1",
    requiredHarnessCheckIds: ["H01"],
    actionOrPoseSetRef: "worldkit://pose-set/runtime-test@1",
    renderBindingProfileRef: "worldkit://render-binding/runtime-test@1",
  };
}

export function createWorldRuntimeBootstrapBodyFixtureV1(): WorldRuntimeBootstrapBodyV1 {
  return {
    kind: "world-runtime-bootstrap",
    schemaVersion: 1,
    id: "world.runtime-test",
    gameplayBootstrapRef: GAMEPLAY_REF,
    gameplayBootstrapHash: HASH_A,
    initialControlledEntityId: "player",
    gravityMetersPerSecondSquaredXYZ: [0, -9.81, 0],
    initialCamera: {
      mode: "third-person",
      cameraEntityId: "camera-main",
      targetEntityId: "player",
      cameraRigProfileRef: "worldkit://camera-profile/runtime-test@1",
      pitchRadians: 0.2,
      distanceMeters: 5,
      targetHeightMeters: 1.5,
      fovDegrees: 60,
      manualSwitchAllowed: true,
    },
    subjectAssets: [{
      subjectAssetRef: "worldkit://subject-asset/runtime-test@1",
      artifactContentHash: HASH_B,
      byteLength: 1024,
      mediaType: "model/gltf-binary",
      format: "glb",
      inventory: {
        meshCount: 1,
        vertexCount: 100,
        triangleCount: 50,
        skeletonCount: 1,
        boneCount: 17,
        animationClipNames: ["Idle"],
      },
    }],
    rigProfiles: [{
      rigProfileRef: "worldkit://rig-profile/runtime-test@1",
      bodyTopology: "biped",
      skeletonRootBoneName: "Armature",
      requiredBoneIds: ["hips"],
      sourceNodeNameByBoneId: {
        hips: "Hips",
      } as unknown as RuntimeRigProfileV1["sourceNodeNameByBoneId"],
    }],
    animationSets: [{
      animationSetRef: "worldkit://animation-set/runtime-test@1",
      subjectAssetRef: "worldkit://subject-asset/runtime-test@1",
      rigProfileRef: "worldkit://rig-profile/runtime-test@1",
      defaultActionId: "idle",
      requiredActionIds: ["idle"],
      animationBindings: [{
        actionId: "idle",
        sourceClipName: "Idle",
        semanticFamily: "ground",
        automaticPresentationKeys: ["locomotion.idle"],
        loopMode: "repeat",
        playbackSpeedRatio: 1,
        blendDurationSeconds: 0.2,
        rootMotionMode: "in-place",
      }],
    }],
    colliderProfiles: [{
      colliderProfileRef: "worldkit://collider-profile/runtime-test@1",
      supportedBodyTopologies: ["biped"],
      collider: {
        kind: "capsule",
        radiusMeters: 0.3,
        heightMeters: 1.8,
        centerOffsetFromSubjectOriginMetersXYZ: [0, 0.9, 0],
      },
    }],
    actionPresentationRegistry: {
      schemaVersion: 1,
      bindings: [actionBinding],
      rootMotionSources: [rootMotionSource],
    },
    subjectRuntimeDescriptors: [{
      entityId: "player",
      subjectDefinitionRef: "worldkit://subject-definition/runtime-test@1",
      subjectDefinitionHash: HASH_A,
      bodyTopology: "biped",
      semanticClassId: "subject.player",
      forwardDirection: "-z",
      visualParts: [{
        id: "model",
        kind: "asset",
        subjectAssetRef: "worldkit://subject-asset/runtime-test@1",
        localTransform: {
          positionMetersXYZ: [0, 0, 0],
          rotationEulerRadiansXYZ: [0, 0, 0],
          scaleXYZ: [1, 1, 1],
        },
        appearance: { mode: "whitebox-neutral" },
        semanticTags: ["controlled-subject"],
      }],
      visualBinding: {
        mode: "rigged",
        rigProfileRef: "worldkit://rig-profile/runtime-test@1",
        animationSetRef: "worldkit://animation-set/runtime-test@1",
      },
      sockets: [
        {
          id: "camera-target",
          kind: "local",
          localTransform: {
            positionMetersXYZ: [0, 1.4, 0],
            rotationEulerRadiansXYZ: [0, 0, 0],
          },
          semanticTags: ["camera"],
        },
        {
          id: "feet",
          kind: "bone",
          boneId: "hips",
          offsetTransform: {
            positionMetersXYZ: [0, -0.9, 0],
            rotationEulerRadiansXYZ: [0, 0, 0],
          },
          semanticTags: ["mount"],
        },
      ],
      mountSlots: [{
        id: "deck-slot",
        kind: "mount-slot",
        mode: "stand",
        mountSocketId: "feet",
        riderSubjectOriginOffsetMetersXYZ: [0, 0, 0],
        dismountCandidateOffsetsMetersXYZ: [[1, 0, 0]],
      }],
      collider: {
        kind: "capsule",
        radiusMeters: 0.3,
        heightMeters: 1.8,
        centerOffsetFromSubjectOriginMetersXYZ: [0, 0.9, 0],
        massKilograms: 75,
        maxSlopeDegrees: 42,
        maxStepHeightMeters: 0.3,
      },
      locomotion: { allowWalk: true, allowRun: true, allowJump: true },
      locomotionCapabilityRef: "worldkit://capability/locomotion.ground@1",
      locomotionCapabilityHash: HASH_A,
      physicsBodyProfileRef: "worldkit://physics-body-profile/runtime-test@1",
      locomotionProfileRef: "worldkit://locomotion-profile/runtime-test@1",
      controlFeel: {
        resourceRef: "worldkit://control-feel-profile/runtime-test@1",
        contentHash: HASH_A,
        jumpVariantPolicy: { mode: "hold-height" },
        walkSpeedMetersPerSecond: 2,
        runSpeedMetersPerSecond: 4,
        jumpSpeedMetersPerSecond: 5,
        accelerationMetersPerSecondSquared: 12,
        decelerationMetersPerSecondSquared: 16,
        turnRateRadiansPerSecond: 8,
        moveResponseExponent: 1,
        airControlRatio: 0.25,
        coyoteTimeSeconds: 0.1,
        jumpBufferSeconds: 0.1,
        variableJumpHoldSeconds: 0.2,
        jumpHoldGravityRatio: 0.5,
        jumpReleaseGravityRatio: 2,
      },
      availableControlFeels: [],
      capabilityAssembly: capabilityAssemblyFixture(),
    }],
    runtimeResourceLockEntries: [
      {
        resourceRef: "worldkit://subject-asset/runtime-test@1",
        resourceKind: "subject-asset",
        resolvedVersion: "1",
        contentHash: HASH_B,
      },
      {
        resourceRef: GAMEPLAY_REF,
        resourceKind: "gameplay-bootstrap",
        resolvedVersion: "1",
        contentHash: HASH_A,
      },
    ],
  };
}
