import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

import {
  parseAcceptedProjectDebtV1,
  parseAcceptedProjectDebtListV1,
  parseIndependentReviewReceiptV1,
  parseProjectHealthAuthorityPolicyV1,
  parseProjectHealthDependencyInventoryV1,
  parseProjectHealthGatePlanV1,
  parseProjectHealthFindingV1,
  parseProjectHealthMetricV1,
  parseProjectHealthObservationV1,
  parseProjectHealthProfileV1,
  parseProjectHealthReportV1,
  parseProjectHealthSupplyChainPolicyV1,
  projectHealthFindingFingerprintV1,
} from "./contracts";
import { sha256CanonicalJson } from "@whitebox-world/protocol";

const HASH_A = `sha256:${"a".repeat(64)}`;
const HASH_B = `sha256:${"b".repeat(64)}`;
const COMMIT_SHA = "c".repeat(40);

const VALID_FINDING_INPUT = {
  sensorId: "contract-parity",
  code: "PROJECT_HEALTH_GENERATED_DRIFT",
  subjectRefs: ["package:builder"],
  evidenceClassIds: ["generated-byte-parity"],
} as const;

const VALID_FINDING = {
  kind: "project-health-finding",
  schemaVersion: 1,
  fingerprint: "sha256:b7ba9113b3d22f687ba293255539ca8adb4c47fbec26336bc579e0f84d780262",
  sensorId: "contract-parity",
  policy: "blocking-p1",
  dimension: "D2",
  code: "PROJECT_HEALTH_GENERATED_DRIFT",
  ownerId: "builder-self-check",
  subjectRefs: ["package:builder"],
  evidenceClassIds: ["generated-byte-parity"],
  metricIds: ["generated-bytes-current"],
  evidenceRefs: [HASH_A],
  expected: "Tracked generated bytes equal the canonical Builder output.",
  impact: "A stale generated bundle can execute behavior different from source.",
  suggestedGateId: "agent-self-check",
} as const;

const VALID_OBSERVATION = {
  kind: "project-health-observation",
  schemaVersion: 1,
  sensorId: "contract-parity",
  sensorImplementationHash: HASH_B,
  inputFingerprint: HASH_A,
  status: "failed",
  metricsById: {
    "generated-bytes-current": {
      id: "generated-bytes-current",
      kind: "boolean",
      value: false,
    },
  },
  findings: [VALID_FINDING],
  evidenceRefs: [HASH_A],
} as const;

const REPOSITORY_ROOT = path.resolve(new URL("../..", import.meta.url).pathname);

function readJson(relativePath: string): unknown {
  return JSON.parse(readFileSync(path.join(REPOSITORY_ROOT, relativePath), "utf8"));
}

function profileContext() {
  const repositoryPaths = execFileSync(
    "git",
    ["ls-files", "--cached", "--others", "--exclude-standard"],
    { cwd: REPOSITORY_ROOT, encoding: "utf8" },
  ).trim().split("\n").filter(Boolean);
  const workspacePackageIds = ["package.json", ...[
    ...readdirSync(path.join(REPOSITORY_ROOT, "packages"), { withFileTypes: true }),
    ...readdirSync(path.join(REPOSITORY_ROOT, "apps"), { withFileTypes: true }),
  ].filter((entry) => entry.isDirectory()).map((entry) => {
    const parent = readdirSync(path.join(REPOSITORY_ROOT, "packages"), { withFileTypes: true })
      .some((candidate) => candidate.name === entry.name)
      ? "packages"
      : "apps";
    return `${parent}/${entry.name}/package.json`;
  })].flatMap((manifestPath) => {
    try {
      const manifest = readJson(manifestPath) as { readonly name?: unknown };
      return typeof manifest.name === "string" ? [manifest.name] : [];
    } catch {
      return [];
    }
  });
  return { repositoryPaths, workspacePackageIds };
}

function parsedProfile() {
  return parseProjectHealthProfileV1(
    readJson("config/project-health/profile.json"),
    profileContext(),
  );
}

function validPrReport() {
  const profile = parsedProfile();
  const selectedSensorIds = [
    "workspace-boundary",
    "supplemental-authority",
    "contract-parity",
    "test-topology",
    "supply-chain",
    "documentation-truth",
  ] as const;
  const sensorImplementationHashesBySensorId = Object.fromEntries(
    selectedSensorIds.map((sensorId) => [sensorId, HASH_A]),
  );
  const observationHashesBySensorId = Object.fromEntries(
    selectedSensorIds.map((sensorId) => [sensorId, HASH_B]),
  );
  return {
    profile,
    report: {
      kind: "project-health-report",
      schemaVersion: 1,
      mode: "pr",
      commitSha: COMMIT_SHA,
      baseSha: null,
      evaluatedOn: "2026-08-31",
      profileHash: sha256CanonicalJson(profile),
      sensorImplementationHashesBySensorId,
      observationHashesBySensorId,
      metricsBySensorId: {
        "workspace-boundary": {
          "workspace-boundary-debt-count": { id: "workspace-boundary-debt-count", kind: "count", valueCount: 49 },
        },
        "supplemental-authority": {
          "supplemental-authority-valid": { id: "supplemental-authority-valid", kind: "boolean", value: true },
        },
        "contract-parity": {
          "generated-bytes-current": { id: "generated-bytes-current", kind: "boolean", value: true },
        },
        "test-topology": {
          "test-census-current": { id: "test-census-current", kind: "boolean", value: true },
        },
        "supply-chain": {
          "dependency-inventory-complete": { id: "dependency-inventory-complete", kind: "boolean", value: true },
        },
        "documentation-truth": {
          "documentation-claims-current": { id: "documentation-claims-current", kind: "boolean", value: true },
        },
      },
      findings: [],
      debtStatesByFingerprint: {},
      status: "passed",
      baselineComparisonStatus: "not-requested",
      changeByFingerprint: null,
    },
  };
}

describe("project health contracts", () => {
  it("rejects an observation containing an absolute path", () => {
    expect(() => parseProjectHealthObservationV1({
      ...VALID_OBSERVATION,
      evidenceRefs: ["file:///Users/example/private.log"],
    }, parsedProfile())).toThrow(/stable evidence reference/i);
  });

  it("rejects a generic absolute host path from stable Finding text", () => {
    expect(() => parseProjectHealthFindingV1({
      ...VALID_FINDING,
      expected: "Read /etc/passwd from the host.",
    }, parsedProfile())).toThrow(/machine paths/i);
  });

  it("rejects unknown observation fields", () => {
    expect(() => parseProjectHealthObservationV1({
      ...VALID_OBSERVATION,
      compatibilityStatus: "passed",
    }, parsedProfile())).toThrow(/closed ProjectHealthObservationV1/i);
  });

  it("fingerprints equivalent subjects independently of input order", () => {
    expect(projectHealthFindingFingerprintV1({
      ...VALID_FINDING_INPUT,
      subjectRefs: ["package:b", "package:a", "package:b"],
    })).toBe(projectHealthFindingFingerprintV1({
      ...VALID_FINDING_INPUT,
      subjectRefs: ["package:a", "package:b"],
    }));
  });

  it("does not fingerprint evidence bytes or their ordering", () => {
    expect(projectHealthFindingFingerprintV1(VALID_FINDING_INPUT)).toBe(
      "sha256:b7ba9113b3d22f687ba293255539ca8adb4c47fbec26336bc579e0f84d780262",
    );
  });

  it("canonicalizes Finding semantic sets independently of input order", () => {
    const profile = parsedProfile();
    const input = {
      ...VALID_FINDING,
      fingerprint: projectHealthFindingFingerprintV1({
        ...VALID_FINDING_INPUT,
        subjectRefs: ["package:b", "package:a"],
        evidenceClassIds: ["generated-byte-parity", "gate-receipt"],
      }),
      subjectRefs: ["package:b", "package:a"],
      evidenceClassIds: ["generated-byte-parity", "gate-receipt"],
      metricIds: ["metric-b", "metric-a"],
      evidenceRefs: [HASH_B, HASH_A],
    };
    const forward = parseProjectHealthFindingV1(input, profile);
    const reverse = parseProjectHealthFindingV1({
      ...input,
      subjectRefs: [...input.subjectRefs].reverse(),
      evidenceClassIds: [...input.evidenceClassIds].reverse(),
      metricIds: [...input.metricIds].reverse(),
      evidenceRefs: [...input.evidenceRefs].reverse(),
    }, profile);
    expect(reverse).toEqual(forward);
    expect(sha256CanonicalJson(reverse)).toBe(sha256CanonicalJson(forward));
  });

  it("rejects overlapping required and advisory gates", () => {
    expect(() => parseProjectHealthGatePlanV1({
      kind: "project-health-gate-plan",
      schemaVersion: 1,
      commitSha: COMMIT_SHA,
      baseSha: null,
      requiredGateIds: ["typecheck"],
      advisoryGateIds: ["typecheck"],
      reasonsByGateId: { typecheck: ["PUBLIC_CONTRACT_CHANGED"] },
      inputFingerprintsByGateId: { typecheck: HASH_A },
    })).toThrow(/disjoint/i);
  });

  it("canonicalizes Gate Plan semantic sets independently of input order", () => {
    const input = {
      kind: "project-health-gate-plan",
      schemaVersion: 1,
      commitSha: COMMIT_SHA,
      baseSha: null,
      requiredGateIds: ["typecheck", "test"],
      advisoryGateIds: ["build", "docs"],
      reasonsByGateId: {
        typecheck: ["PUBLIC_CONTRACT_CHANGED", "SOURCE_CHANGED"],
        test: ["SOURCE_CHANGED", "PUBLIC_CONTRACT_CHANGED"],
        build: ["BUILD_INPUT_CHANGED"],
        docs: ["DOCUMENTATION_CHANGED"],
      },
      inputFingerprintsByGateId: {
        typecheck: HASH_A,
        test: HASH_B,
        build: HASH_A,
        docs: HASH_B,
      },
    } as const;
    const reverse = {
      ...input,
      requiredGateIds: [...input.requiredGateIds].reverse(),
      advisoryGateIds: [...input.advisoryGateIds].reverse(),
      reasonsByGateId: Object.fromEntries(Object.entries(input.reasonsByGateId).map(
        ([gateId, reasons]) => [gateId, [...reasons].reverse()],
      )),
    };
    expect(parseProjectHealthGatePlanV1(reverse)).toEqual(parseProjectHealthGatePlanV1(input));
  });

  it("rejects blocking accepted debt and invalid metric caps", () => {
    const debt = {
      kind: "accepted-project-debt",
      schemaVersion: 1,
      fingerprint: HASH_A,
      acceptedPolicy: "blocking-p1",
      metricCapsById: {
        "bundle-ratio": { kind: "ratio", maximumRatio: 1.1 },
      },
      ownerId: "runtime-owner",
      decisionRef: "docs/decisions/ADR-0001.md",
      reason: "A temporary exception with a bounded removal gate.",
      expiresOn: "2026-09-30",
    };
    expect(() => parseAcceptedProjectDebtV1(debt, parsedProfile())).toThrow(/advisory debt/i);
    expect(() => parseAcceptedProjectDebtV1({
      ...debt,
      acceptedPolicy: "advisory-p2",
    }, parsedProfile())).toThrow(/ratio/i);
  });

  it("requires independent review dispositions to close exactly over candidates", () => {
    expect(() => parseIndependentReviewReceiptV1({
      kind: "independent-review-receipt",
      schemaVersion: 1,
      commitSha: COMMIT_SHA,
      reviewerId: "cursor-cloud",
      status: "completed",
      candidateFindings: [VALID_FINDING],
      dispositionsByFingerprint: {},
      evidenceRef: HASH_A,
    }, parsedProfile())).toThrow(/disposition/i);
  });

  it("rejects conflicting licenses for one exact dependency", () => {
    expect(() => parseProjectHealthDependencyInventoryV1({
      kind: "project-health-dependency-inventory",
      schemaVersion: 1,
      commitSha: COMMIT_SHA,
      packageManagerId: "pnpm@10.14.0",
      commandHash: HASH_A,
      inputFingerprint: HASH_B,
      entries: [
        { id: "example@1.0.0", packageName: "example", version: "1.0.0", licenseSpdxExpression: "MIT" },
        { id: "example@1.0.0", packageName: "example", version: "1.0.0", licenseSpdxExpression: "Apache-2.0" },
      ],
    })).toThrow(/conflicting license/i);
  });

  it("rejects a host path masquerading as a dependency package name", () => {
    expect(() => parseProjectHealthDependencyInventoryV1({
      kind: "project-health-dependency-inventory",
      schemaVersion: 1,
      commitSha: COMMIT_SHA,
      packageManagerId: "pnpm@10.14.0",
      commandHash: HASH_A,
      inputFingerprint: HASH_B,
      entries: [
        { id: "/etc/passwd@1.0.0", packageName: "/etc/passwd", version: "1.0.0", licenseSpdxExpression: "MIT" },
      ],
    })).toThrow(/DependencyInventoryV1/i);
  });

  it("parses the one current Profile against the exact repository tree", () => {
    expect(parseProjectHealthProfileV1(
      readJson("config/project-health/profile.json"),
      profileContext(),
    ).id).toBe("worldkit-project-health");
  });

  it("canonicalizes Profile selector and reason sets independently of input order", () => {
    const input = readJson("config/project-health/profile.json") as {
      inputSelectorsBySensorId: Record<string, { exactPaths: string[] }>;
      capabilitySelectorsById: Record<string, { pathPrefixes: string[] }>;
      metricPoliciesById: Record<string, { notApplicableReasonCodes: string[] }>;
    };
    const reverse = structuredClone(input);
    reverse.inputSelectorsBySensorId["workspace-boundary"]!.exactPaths.reverse();
    reverse.capabilitySelectorsById["native-scene-experimental"]!.pathPrefixes.reverse();
    reverse.metricPoliciesById["visual-golden-diff-ratio"]!.notApplicableReasonCodes.reverse();
    expect(parseProjectHealthProfileV1(reverse, profileContext())).toEqual(
      parseProjectHealthProfileV1(input, profileContext()),
    );
  });

  it.each(["packages/studio", "scripts/native-scene-missing"]) (
    "rejects a capability selector entry that matches no current path: %s",
    (deadPath) => {
      const profile = readJson("config/project-health/profile.json") as {
        capabilitySelectorsById: Record<string, {
          exactPaths: string[];
          pathPrefixes: string[];
          pathSuffixes: string[];
          packageIds: string[];
        }>;
      };
      const invalid = structuredClone(profile);
      invalid.capabilitySelectorsById["studio-surface"]!.pathPrefixes.push(deadPath);
      expect(() => parseProjectHealthProfileV1(invalid, profileContext())).toThrow(
        /PROJECT_HEALTH_CAPABILITY_SELECTOR_EMPTY/,
      );
    },
  );

  it("rejects a capability Gate closure that differs from the frozen design", () => {
    const profile = readJson("config/project-health/profile.json") as {
      capabilityGateIdsById: Record<string, string[]>;
    };
    const invalid = structuredClone(profile);
    invalid.capabilityGateIdsById["native-scene-experimental"] = ["canonical"];
    expect(() => parseProjectHealthProfileV1(invalid, profileContext())).toThrow(
      /capability Gate closure/i,
    );
  });

  it("rejects a PR Sensor closure that promotes dynamic runtime work", () => {
    const profile = readJson("config/project-health/profile.json") as {
      modesById: { pr: { requiredSensorIds: string[] } };
    };
    const invalid = structuredClone(profile);
    invalid.modesById.pr.requiredSensorIds.push("runtime-health");
    expect(() => parseProjectHealthProfileV1(invalid, profileContext())).toThrow(/mode Sensor closure/i);
  });

  it("rejects non-canonical capability suffixes", () => {
    const profile = readJson("config/project-health/profile.json") as {
      capabilitySelectorsById: Record<string, { pathSuffixes: string[] }>;
    };
    const invalid = structuredClone(profile);
    invalid.capabilitySelectorsById["test-registration"]!.pathSuffixes.push("/package.json");
    expect(() => parseProjectHealthProfileV1(invalid, profileContext())).toThrow(/canonical path suffix/i);
  });

  it("rejects negative zero in a stable Metric", () => {
    expect(() => parseProjectHealthMetricV1({
      id: "runtime-owner-leak-count",
      kind: "count",
      valueCount: -0,
    })).toThrow(/ProjectHealthMetricV1/);
  });

  it("derives Observation Finding policy from the exact Profile", () => {
    const profile = parsedProfile();
    expect(parseProjectHealthObservationV1(VALID_OBSERVATION, profile)).toEqual(VALID_OBSERVATION);
    expect(() => parseProjectHealthObservationV1({
      ...VALID_OBSERVATION,
      findings: [{ ...VALID_FINDING, policy: "advisory-p3" }],
    }, profile)).toThrow(/Profile Finding policy/i);
  });

  it("derives Observation status and not-applicable reasons from the exact Profile", () => {
    const profile = parsedProfile();
    expect(() => parseProjectHealthObservationV1({
      ...VALID_OBSERVATION,
      status: "passed",
    }, profile)).toThrow(/derived Observation status/i);
    expect(() => parseProjectHealthObservationV1({
      ...VALID_OBSERVATION,
      status: "passed",
      metricsById: {
        "generated-bytes-current": {
          id: "generated-bytes-current",
          kind: "boolean",
          status: "not-applicable",
          reasonCode: "MADE_UP_REASON",
        },
      },
      findings: [],
    }, profile)).toThrow(/not-applicable reason/i);
    expect(() => parseProjectHealthObservationV1({
      ...VALID_OBSERVATION,
      status: "passed",
      metricsById: {
        "generated-bytes-current": {
          id: "generated-bytes-current",
          kind: "boolean",
          value: true,
        },
      },
      findings: [],
    }, profile)).not.toThrow();
  });

  it("rejects an Independent Review candidate that lies about Profile policy", () => {
    const candidate = { ...VALID_FINDING, policy: "advisory-p3" };
    expect(() => parseIndependentReviewReceiptV1({
      kind: "independent-review-receipt",
      schemaVersion: 1,
      commitSha: COMMIT_SHA,
      reviewerId: "cursor-cloud",
      status: "completed",
      candidateFindings: [candidate],
      dispositionsByFingerprint: {
        [candidate.fingerprint]: "host-confirmed",
      },
      evidenceRef: HASH_A,
    }, parsedProfile())).toThrow(/Profile Finding policy/i);
  });

  it("rejects accepted debt cap kind and ceiling drift from the exact Profile", () => {
    const profile = parsedProfile();
    const debt = {
      kind: "accepted-project-debt",
      schemaVersion: 1,
      fingerprint: HASH_A,
      acceptedPolicy: "advisory-p2",
      metricCapsById: {
        "bundle-bytes": { kind: "count", maximumCount: 1 },
      },
      ownerId: "performance-owner",
      decisionRef: "docs/decisions/ADR-0001.md",
      reason: "A bounded exception pending the accepted removal gate.",
      expiresOn: "2026-09-30",
    };
    expect(() => parseAcceptedProjectDebtV1(debt, profile)).toThrow(/Metric kind/i);
    expect(() => parseAcceptedProjectDebtV1({
      ...debt,
      metricCapsById: {
        "bundle-bytes": { kind: "bytes", maximumBytes: 52428801 },
      },
    }, profile)).toThrow(/Profile maximum/i);
  });

  it("requires Report maps and Metrics to close over the selected mode", () => {
    const { profile, report } = validPrReport();
    expect(parseProjectHealthReportV1(report, profile)).toEqual(report);
    const invalid = structuredClone(report);
    delete (invalid.metricsBySensorId as Record<string, unknown>)["supply-chain"];
    expect(() => parseProjectHealthReportV1(invalid, profile)).toThrow(/selected Sensor closure/i);
  });

  it("derives final Report status from Required Metrics and blocking Findings", () => {
    const { profile, report } = validPrReport();
    const failedMetric = structuredClone(report);
    failedMetric.metricsBySensorId["contract-parity"]!["generated-bytes-current"] = {
      id: "generated-bytes-current",
      kind: "boolean",
      value: false,
    };
    expect(() => parseProjectHealthReportV1(failedMetric, profile)).toThrow(/derived Report status/i);

    const incompleteMetric = structuredClone(report);
    (incompleteMetric.metricsBySensorId["contract-parity"] as Record<string, unknown>)["generated-bytes-current"] = {
      id: "generated-bytes-current",
      kind: "boolean",
      status: "not-evaluated",
      reasonCode: "OWNER_COMMAND_NOT_RUN",
    };
    expect(() => parseProjectHealthReportV1(incompleteMetric, profile)).toThrow(/derived Report status/i);
  });

  it("parses the three current Policy and debt configuration files", () => {
    const profile = parsedProfile();
    const authorityPolicy = parseProjectHealthAuthorityPolicyV1(
      readJson("config/project-health/authority-policy.json"),
      profile,
    );
    expect(authorityPolicy.exceptions).toEqual([]);
    expect(authorityPolicy.rules.map((rule) => rule.id)).toEqual([
      "public-compat-alias",
      "public-protocol-single-parser-owner",
      "scene-source-single-owner",
    ]);
    expect(parseProjectHealthSupplyChainPolicyV1(
      readJson("config/project-health/supply-chain-policy.json"),
    ).advisoryProviderIds).toEqual(["osv"]);
    expect(parseAcceptedProjectDebtListV1(
      readJson("config/project-health/accepted-debt.json"),
      profile,
    ).entries).toEqual([]);
  });

  it("rejects workspace-edge debt or package-version waivers in Project Health Policy", () => {
    const profile = parsedProfile();
    expect(() => parseProjectHealthAuthorityPolicyV1({
      ...(readJson("config/project-health/authority-policy.json") as object),
      workspaceBoundaryDebtEntries: [],
    }, profile)).toThrow(/closed ProjectHealthAuthorityPolicyV1/i);
    expect(() => parseProjectHealthSupplyChainPolicyV1({
      ...(readJson("config/project-health/supply-chain-policy.json") as object),
      packageVersionWaivers: [],
    })).toThrow(/closed ProjectHealthSupplyChainPolicyV1/i);
  });

  it("never parses Profile-bound contracts without their exact validation authority", () => {
    const profileInput = readJson("config/project-health/profile.json");
    const { profile, report } = validPrReport();
    expect(() => parseProjectHealthProfileV1(profileInput, undefined as never)).toThrow(/exact tree context/i);
    expect(() => parseProjectHealthObservationV1(VALID_OBSERVATION, undefined as never)).toThrow(/exact Profile/i);
    expect(() => parseProjectHealthReportV1(report, undefined as never)).toThrow(/exact Profile/i);
    expect(() => parseAcceptedProjectDebtListV1(
      readJson("config/project-health/accepted-debt.json"),
      undefined as never,
    )).toThrow(/exact Profile/i);
    expect(() => parseProjectHealthAuthorityPolicyV1(
      readJson("config/project-health/authority-policy.json"),
      undefined as never,
    )).toThrow(/exact Profile/i);
    expect(profile.id).toBe("worldkit-project-health");
  });

  it.each([
    "See /Users/example/private.log for details.",
    "Provider returned token=crsr_abcdefghijklmnopqrstuvwxyz.",
  ])("rejects unstable machine or credential text from a Finding: %s", (impact) => {
    expect(() => parseProjectHealthObservationV1({
      ...VALID_OBSERVATION,
      findings: [{ ...VALID_FINDING, impact }],
    }, parsedProfile())).toThrow(/stable Project Health text/i);
  });
});
