import {episodeScheduling,EPISODE_SCHEDULING_VERSION} from '../cloud/three-episode-scheduling.mjs';
import {parseGpuCaptureBatchManifest} from '../lib/cloud-production-run.mjs';
export function captureBatchJob({batch,cohortId,namespace='lwdp'}){
  const admitted=parseGpuCaptureBatchManifest(batch);
  if(admitted.taskCount>100||!['capacity-threshold','producer-complete'].includes(admitted.dispatchReason))throw Error('EPISODE_BATCH_ADMISSION_INVALID');
  if(!/^[a-z0-9][a-z0-9-]{2,119}$/.test(cohortId??''))throw Error('EPISODE_COHORT_INVALID');
  const deadline=600+admitted.taskCount*900;
  return {apiVersion:'batch/v1',kind:'Job',metadata:{name:`three-${batch.batchId}`,namespace,labels:{'app.kubernetes.io/name':'worldkit-three-episode-capture'},annotations:{'worldkit.seedleap.dev/batch-hash':batch.batchHash}},spec:{parallelism:1,completions:1,backoffLimit:0,podReplacementPolicy:'Failed',activeDeadlineSeconds:deadline,ttlSecondsAfterFinished:3600,template:{metadata:{labels:{'app.kubernetes.io/name':'worldkit-three-episode-capture','worldkit.seedleap.dev/profile':EPISODE_SCHEDULING_VERSION}},spec:{serviceAccountName:'worldkit-three-capture',restartPolicy:'Never',terminationGracePeriodSeconds:60,...episodeScheduling({gpuCount:1}),containers:[{name:'capture-batch',image:batch.workerImage,command:['node','scripts/three-episode/batch-cli.mjs'],args:['worker','--cohort',cohortId,'--batch',batch.batchId,'--namespace',namespace],env:[{name:'WORLDKIT_CAPTURE_GPU',value:'1'},{name:'NVIDIA_DRIVER_CAPABILITIES',value:'compute,utility,graphics'},{name:'PLAYWRIGHT_BROWSERS_PATH',value:'/ms-playwright'},{name:'WORLDKIT_BATCH_POD',valueFrom:{fieldRef:{fieldPath:'metadata.name'}}}],resources:{requests:{cpu:'4',memory:'12Gi','nvidia.com/gpu':1,'ephemeral-storage':'32Gi'},limits:{cpu:'6',memory:'20Gi','nvidia.com/gpu':1,'ephemeral-storage':'64Gi'}},volumeMounts:[{name:'workspace',mountPath:'/episode-batch'},{name:'runtime',mountPath:'/var/run/worldkit-episode-runtime',readOnly:true}]}],volumes:[{name:'workspace',emptyDir:{}},{name:'runtime',secret:{secretName:'worldkit-episode-runtime',items:[{key:'aws-config',path:'aws-config'},{key:'aws-credentials',path:'aws-credentials'}]}}]}}}};
}
