import { copyFile, mkdir, readFile, writeFile, rename, stat } from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';

const esc = (value: unknown) => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
async function json(file: string): Promise<any> { try {return JSON.parse(await readFile(file,'utf8'));}catch(error:any){if(error.code==='ENOENT')return null;throw error;} }
export async function renderEpisodeReport({outputRoot,state}:{outputRoot:string;state:any}) {
 const root=path.join(outputRoot,'report');await mkdir(path.join(root,'assets'),{recursive:true});
 async function asset(file:string|undefined){if(!file)return null;try{const bytes=await readFile(file),name=createHash('sha256').update(bytes).digest('hex')+path.extname(file);const target=path.join(root,'assets',name);try{await stat(target);}catch{await copyFile(file,target);}return `assets/${name}`;}catch(error:any){if(error.code==='ENOENT')return null;throw error;}}
 const segments=[];
 for(const segment of state.segments??[]){const video=segment.artifacts?.find((f:any)=>f.path==='video.mp4');const first=segment.artifacts?.find((f:any)=>f.path==='first-frame.png');
  const health=await json(path.join(segment.outputRoot,'health.json'));
  segments.push({playerBehavior:health?.playerBehavior??null,playerCaptureVersion:health?.playerCaptureVersion??null,id:segment.segmentId,status:segment.status,video:video?await asset(path.join(segment.outputRoot,video.path)):null,first:first?await asset(path.join(segment.outputRoot,first.path)):null,error:segment.failure??null});}
 const variants=[];
 for(let i=0;i<10;i++){const id=`style-0${i}`,manifest=await json(path.join(outputRoot,'visuals','variants',id,'visual-manifest.json'));
  const progress=state.visualState?.variants?.find((item:any)=>item.id===id);
  const openings=[];for(const image of manifest?.openings??[])openings.push(await asset(image.path));
  const triviews=[];for(const image of manifest?.styledTriviews??[])triviews.push({id:image.targetId,image:await asset(image.path)});
  variants.push({id,styleMode:manifest?.variant?.styleMode??null,referenceImageSha256:manifest?.variant?.referenceImageSha256??null,status:progress?.stage??'pending',name:manifest?.variant?.name??manifest?.variant?.title??id,openings,triviews});}
 const data={episodeId:state.episodeId,worldId:state.worldId,status:state.status,stage:state.stage,updatedAt:state.updatedAt,
  anchorAdmission:state.anchorAdmission??(state.visualState?.userAcceptedAnchors?.length?{acceptedCount:state.visualState.userAcceptedAnchors.length,authority:'user'}:null),
  sourceWorldBuildHash:state.sourceWorldBuildHash,worldBuildHash:state.worldBuildHash,segments,variants,error:state.error??null,preparedRequestCount:state.preparedRequestCount??0,providerVideoSubmissionCount:0};
 const statusFile=path.join(root,'status.json');await writeFile(`${statusFile}.part`,JSON.stringify(data,null,2));await rename(`${statusFile}.part`,statusFile);
 const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Episode · ${esc(state.worldId)}</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f5f7;color:#17232e;font:15px/1.6 system-ui,-apple-system,sans-serif}main{max-width:1440px;margin:auto;padding:32px}header{display:flex;justify-content:space-between;align-items:center;gap:20px}h1{font-size:28px;margin:6px 0}h2{font-size:19px;margin:32px 0 12px}.sub{color:#617182}.pill{background:#e3eefb;color:#15579b;padding:8px 14px;border-radius:24px;white-space:nowrap}.notice{padding:14px 18px;background:#fff;border-left:4px solid #4082c6;margin:22px 0;border-radius:6px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:18px}.card{background:white;border:1px solid #dfe5eb;border-radius:12px;overflow:hidden}.card header{padding:13px 16px;font-weight:650}.card p{padding:0 16px;color:#617182}.card video,.card img{width:100%;display:block;background:#e4e9ee}.empty{padding:45px 16px;text-align:center;color:#7c8793}.tag{font-size:12px;font-weight:500;color:#5c6b79}.thumbs{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;padding:8px}.error{background:#fff0ee;color:#8c3025;padding:16px;border-radius:8px;white-space:pre-wrap}.mono{font:12px ui-monospace,monospace;overflow-wrap:anywhere}details{padding:0 12px 12px}summary{cursor:pointer;color:#467297}.stats{display:flex;gap:30px;flex-wrap:wrap}.stats strong{font-size:24px;display:block}.foot{margin-top:30px;color:#76818b;font-size:12px}@media(max-width:650px){main{padding:16px}header{align-items:flex-start;flex-direction:column}}
</style><main><header><div><div class="sub">独立数据生产 · 原世界仍可游玩</div><h1>${esc(state.worldId)}</h1><div class="sub">${esc(state.episodeId)}</div></div><div class="pill" id="stage"></div></header><div class="notice">本次流程停在 Seedance 提交之前。下方展示真实白模录像、样式图片与生产状态。</div><div id="stats" class="stats"></div><div id="error"></div><h2>六段白模录制</h2><div id="segments" class="grid"></div><h2>十种样式</h2><div id="variants" class="grid"></div><details class="foot"><summary>来源版本</summary><p class="mono">原世界：${esc(state.sourceWorldBuildHash)}<br>产数副本：${esc(state.worldBuildHash)}</p></details></main><script>
const escapeHtml=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const names={'review-calibrated':'审核标准已校准','awaiting-reevaluation':'等待复评',queued:'排队中',planning:'Agent 规划路线',planned:'路线已提交','whitebox-capture':'录制白模','route-repair':'Agent 修复失败路线','route-repaired':'路线已修复','style-planning':'规划十种样式',anchors:'生成样式锚点','opening-anchors':'生成与检查样式锚点','opening-anchor':'生成样式锚点',visuals:'生成首帧与三视图','diversity-review':'样式差异检查','visual-events':'准备视觉事件','pre-seedance-ready':'渲染准备完成','appearance-lock':'提取已审核外观','style-images':'生成样式图片','style-review':'检查样式图片','images-ready':'样式图片就绪','anchor-repair':'修正样式锚点',completed:'完成',failed:'失败',pending:'等待中',prepared:'等待与你对齐'};
let last='';async function refresh(){try{const d=await fetch('status.json?t='+Date.now()).then(r=>r.json());if(d.updatedAt===last)return;last=d.updatedAt;document.getElementById('stage').textContent=(d.stage==='planning'&&d.segments.length===6?'规划十种样式':d.stage==='opening-anchors'&&d.variants.some(v=>['style-images','style-review','images-ready','pre-seedance-ready'].includes(v.status))?'生成样式首帧与三视图':names[d.stage]??d.stage)+' · '+(names[d.status]??d.status);document.getElementById('stats').innerHTML='<div><strong>'+d.segments.filter(s=>s.status==='completed').length+' / 6</strong>白模录像</div><div><strong>'+d.variants.filter(v=>v.openings.length===6).length+' / 10</strong>完整样式图片组</div><div><strong>'+d.preparedRequestCount+' / 60</strong>渲染请求已准备</div><div><strong>0</strong>Seedance 提交</div>';if(d.anchorAdmission)document.getElementById('stats').innerHTML+='<div><strong>'+d.anchorAdmission.acceptedCount+' / 10</strong>用户确认通过的锚点</div>';document.getElementById('error').innerHTML=d.error?'<p class="error">'+escapeHtml(d.error.message??d.error)+'</p>':'';
document.getElementById('segments').innerHTML=Array.from({length:6},(_,i)=>{const id='segment-0'+i,s=d.segments.find(s=>s.id===id);return '<article class="card"><header>'+id+'<span class="tag">'+escapeHtml(names[s?.status]??s?.status??'等待录制')+'</span></header>'+(s?.video?'<video controls preload="none"'+(s.first?' poster="'+s.first+'"':'')+' src="'+s.video+'"></video>':'<div class="empty">等待真实录像</div>')+(s?.playerBehavior?'<p>镜头横向覆盖 '+Math.round(s.playerBehavior.renderedYawRangeDegrees)+'° · 行走 '+s.playerBehavior.walkSeconds.toFixed(1)+'s · 跑动 '+s.playerBehavior.runSeconds.toFixed(1)+'s<br>主动跳跃完成 '+s.playerBehavior.plannedJumps.filter(j=>j.takeoffAtSeconds!==null&&j.landedAtSeconds!==null).length+' 次</p>':'')+(s?.error?'<p>'+escapeHtml(s.error.message)+'</p>':'')+'</article>';}).join('');
document.getElementById('variants').innerHTML=d.variants.map(v=>'<article class="card"><header>'+(v.styleMode==='source-reference'&&!v.name.includes('原图风格')?'原图风格 · ':'')+escapeHtml(v.name)+'<span class="tag">'+escapeHtml(names[v.status]??v.status)+'</span></header>'+(v.openings[0]?'<a target="_blank" href="'+v.openings[0]+'"><img loading="lazy" src="'+v.openings[0]+'"></a>':'<div class="empty">等待样式图片</div>')+'<div class="thumbs">'+v.openings.slice(1).filter(Boolean).map(p=>'<a target="_blank" href="'+p+'"><img loading="lazy" src="'+p+'"></a>').join('')+'</div>'+(v.triviews.length?'<details><summary>完整目标三视图 · '+v.triviews.length+'</summary>'+v.triviews.map(t=>'<p>'+escapeHtml(t.id)+'</p><a target="_blank" href="'+t.image+'"><img loading="lazy" src="'+t.image+'"></a>').join('')+'</details>':'')+'</article>').join('');}catch(e){document.getElementById('stage').textContent='等待生产状态';}}refresh();setInterval(refresh,10000);
</script></html>`;
 const file=path.join(root,'index.html');await writeFile(`${file}.part`,html);await rename(`${file}.part`,file);
 return root;
}
