import {describe,it,expect} from 'vitest';
import {mkdtemp,writeFile,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {planCameraMigration,writeCameraMigration,sourceSha256,rewriteKnownCameraCall} from './camera-configuration';
const source=(camera:Record<string,unknown>={},context:Record<string,unknown>={})=>({sourcePath:'profiles.json',sourceBytes:JSON.stringify(camera),context:{targetEntityId:'person',subject:'humanoid',...context}});
describe('one-time camera migration',()=>{
 it('preserves humanoid calibration, hidden opening and range',()=>{const plan=planCameraMigration(source({baseFovDegrees:58,distance:8.8},{distanceIntent:'explicit'})); const v=plan.document.views['third-person']!;expect(v.overrides?.lens?.verticalFovDegrees).toBe(58);expect(v.overrides?.orientation?.initialPitchRadians).toBe(.35);expect(v.overrides?.position?.anchor).toEqual({kind:'follow-pivot'});expect(v.overrides?.position).toMatchObject({distanceMeters:8.8});});
 it('preserves zero vehicle arm and converts zero recenter to disabled',()=>{const p=planCameraMigration(source({distance:0,recenterResponsePerSecond:0},{subject:'vehicle',speed:30}));expect(p.document.views['third-person']!.overrides).toMatchObject({position:{distanceMeters:0},orientation:{recenter:{enabled:false}},zoom:{range:{minimumDistanceMeters:0,maximumDistanceMeters:0}}});});
 it('splits shared zoom/recovery and world target height without conflating local offsets',()=>{const p=planCameraMigration(source({recoveryHalfLifeSeconds:.24,targetHeightMeters:2},{subject:'public'}));expect(p.document.views['third-person']!.overrides).toMatchObject({zoom:{halfLifeSeconds:.24},constraints:{recovery:{halfLifeSeconds:.24}},position:{anchor:{kind:'origin'},anchorOffset:{space:'world',offsetMetersXYZ:[0,2,0]}}});});
 it('reports explicit 8.8 ambiguity and unsupported custom source with location',()=>{const p=planCameraMigration(source({distance:8.8,custom:1}));expect(p.report.some(r=>r.status==='unknown'&&r.field==='distance')).toBe(true);expect(p.report.some(r=>r.status==='unknown'&&r.field==='custom')).toBe(true);});
 it('preserves two independently named third-person views',()=>{const p=planCameraMigration(source({distance:4},{subject:'public',viewIds:['wide','close']}));expect(Object.keys(p.document.views)).toEqual(['wide','close']);expect(p.document.defaultViewId).toBe('wide');});
 it('rewrites only exact inventoried source ranges and reports changed custom calls',()=>{const text='world.setCameraFollow({distanceMeters:4})',plan=planCameraMigration(source({distance:4},{subject:'public'}));const site={path:'main.ts',start:0,end:text.length,expectedCall:text,worldExpression:'world'};expect(rewriteKnownCameraCall(text,site,plan).source).toContain('configuration:');expect(rewriteKnownCameraCall(text+'x',{...site,expectedCall:'unknown'},plan).report.status).toBe('conflict');});
 it('distinguishes omitted, null and explicit world distance in legacy profiles',()=>{const make=(value:unknown)=>planCameraMigration({sourcePath:'old.json',sourceBytes:JSON.stringify(value),context:{targetEntityId:'person',subject:'humanoid',mapDistanceMeters:5.6}});expect(make({camera:{distance:8.8},cameraDistanceMeters:null}).document.views['third-person']!.overrides?.position).toMatchObject({distanceMeters:5.6});expect(make({camera:{distance:8.8},cameraDistanceMeters:9}).document.views['third-person']!.overrides?.position).toMatchObject({distanceMeters:9});expect(make({camera:{distance:8.8}}).report.some(r=>r.field==='cameraDistanceMeters'&&r.status==='inactive')).toBe(true);});
 it.each([
  {camera:{collisionRadiusMeters:'bad'},cameraDistanceMeters:'bad'},
  {collisionRadiusMeters:'bad'}, {collisionEnabled:1}, {activateOnInput:null},
  {cameraDistanceMeters:'bad'}, {cameraDistanceMeters:false},
  {view:{keyboardToggleEnabled:'yes'}}, {view:{defaultPerspective:1}},
  {mode:1.5}, {mode:'1'}, {view:[]}, {camera:[]}, {camera:null},
  {opening:null}, {maximumRecoveryMetersPerSecond:-1},
 ])('rejects malformed consumed legacy input %j',(value)=>{expect(()=>planCameraMigration({...source(),sourceBytes:JSON.stringify(value)})).toThrow('LEGACY_FIELD_INVALID');});
 it('reports unknown nested-wrapper fields with original source paths',()=>{const p=planCameraMigration({...source(),sourceBytes:JSON.stringify({camera:{customSetting:2},customWrapper:{nested:3},view:{unknownToggle:true},control:{speed:5}})});for(const field of ['camera.customSetting','customWrapper.nested','view.unknownToggle','control.speed'])expect(p.report).toContainEqual(expect.objectContaining({field,status:'unknown'}));});
 it('retains unknown fields inside known wrapper objects with their exact location',()=>{const p=planCameraMigration({...source(),sourceBytes:JSON.stringify({camera:{opening:{positionWorldMetersXYZ:[0,3,8],lookAtWorldMetersXYZ:[0,1,0],fovDegrees:55,extra:'retain'}},view:{collisionEnabled:'not-a-view-field'}})});expect(p.report).toContainEqual(expect.objectContaining({field:'camera.opening.extra',status:'unknown'}));expect(p.report).toContainEqual(expect.objectContaining({field:'view.collisionEnabled',status:'unknown'}));expect(p.document.views['third-person']).toHaveProperty('opening.fovDegrees',55);});
 it.each([{nearMeters:null},{speed:'bad'},{creature:'yes'},{flyingCreature:1},{seat:[0,'bad',0]},{distanceIntent:'guess'}])('rejects malformed consumed source context %j',(context)=>{expect(()=>planCameraMigration(source({},context))).toThrow('LEGACY_FIELD_INVALID:context.');});
 it('is byte deterministic and verifies original source before writing',async()=>{const dir=await mkdtemp(join(tmpdir(),'camera-migrate-'));const path=join(dir,'old.json');const input={...source({distance:4},{subject:'public'}),sourcePath:path};await writeFile(path,input.sourceBytes);const a=planCameraMigration(input),b=planCameraMigration(input);expect(a.documentBytes).toBe(b.documentBytes);expect(a.sourceHash).toBe(sourceSha256(input.sourceBytes));await writeCameraMigration(a,join(dir,'camera.json'));expect(await readFile(join(dir,'camera.json'),'utf8')).toBe(a.documentBytes);await writeFile(path,'{}');await expect(writeCameraMigration(a,join(dir,'camera.json'))).rejects.toThrow('SOURCE_HASH_CONFLICT');});
});
