import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync } from "node:fs";
import { readFile as readFileAsync } from "node:fs/promises";
import path from "node:path";

import { describe, expect, it } from "vitest";

import {
  parseIndependentReviewReceiptV1,
  parseProjectHealthProfileV1,
  projectHealthFindingFingerprintV1,
  type IndependentReviewReceiptV1,
  type ProjectHealthFindingV1,
} from "../contracts";
import { observeIndependentReviewV1 } from "./independent-review";

const REPOSITORY_ROOT = path.resolve(new URL("../../..", import.meta.url).pathname);
const COMMIT_SHA = "a".repeat(40);
const WRONG_SHA = "b".repeat(40);
const HASH_A = `sha256:${"a".repeat(64)}`;

const CANDIDATE: ProjectHealthFindingV1 = {
  kind: "project-health-finding",
  schemaVersion: 1,
  fingerprint: projectHealthFindingFingerprintV1({
    sensorId: "contract-parity",
    code: "PROJECT_HEALTH_GENERATED_DRIFT",
    subjectRefs: ["package:builder"],
    evidenceClassIds: ["generated-byte-parity"],
  }),
  sensorId: "contract-parity",
  policy: "blocking-p1",
  dimension: "D2",
  code: "PROJECT_HEALTH_GENERATED_DRIFT",
  ownerId: "builder-self-check",
  subjectRefs: ["package:builder"],
  evidenceClassIds: ["generated-byte-parity"],
  metricIds: ["generated-bytes-current"],
  evidenceRefs: [HASH_A],
  expected: "Tracked generated bytes equal the canonical Builder output.",
  impact: "A stale generated bundle can execute behavior different from source.",
  suggestedGateId: "agent-self-check",
};

function readJson(relativePath: string): unknown {
  return JSON.parse(readFileSync(path.join(REPOSITORY_ROOT, relativePath), "utf8"));
}

function parsedProfile() {
  const repositoryPaths = execFileSync(
    "git",
    ["ls-files", "--cached", "--others", "--exclude-standard"],
    { cwd: REPOSITORY_ROOT, encoding: "utf8" },
  ).trim().split("\n").filter(Boolean);
  const workspacePackageIds = ["package.json", ...[
    ...readdirSync(path.join(REPOSITORY_ROOT, "packages"), { withFileTypes: true }),
    ...readdirSync(path.join(REPOSITORY_ROOT, "apps"), { withFileTypes: true }),
  ].filter((entry) => entry.isDirectory()).map((entry) => {
    const parent = readdirSync(path.join(REPOSITORY_ROOT, "packages"), { withFileTypes: true })
      .some((candidate) => candidate.name === entry.name)
      ? "packages"
      : "apps";
    return `${parent}/${entry.name}/package.json`;
  })].flatMap((manifestPath) => {
    try {
      const manifest = readJson(manifestPath) as { readonly name?: unknown };
      return typeof manifest.name === "string" ? [manifest.name] : [];
    } catch {
      return [];
    }
  });
  return parseProjectHealthProfileV1(readJson("config/project-health/profile.json"), {
    repositoryPaths,
    workspacePackageIds,
  });
}

function receipt(
  overrides: Partial<IndependentReviewReceiptV1> = {},
): IndependentReviewReceiptV1 {
  return parseIndependentReviewReceiptV1({
    kind: "independent-review-receipt",
    schemaVersion: 1,
    commitSha: COMMIT_SHA,
    reviewerId: "cursor-cloud",
    status: "completed",
    candidateFindings: [],
    dispositionsByFingerprint: {},
    evidenceRef: HASH_A,
    ...overrides,
  }, parsedProfile());
}

describe("independent-review sensor", () => {
  it("does not treat an AI GO string as pass evidence", async () => {
    const source = await readFileAsync(new URL("./independent-review.ts", import.meta.url), "utf8");
    expect(source).not.toMatch("child_process");
    expect(source).not.toMatch(/\bGO\b/);
    const observation = observeIndependentReviewV1({
      profile: parsedProfile(),
      expectedCommitSha: COMMIT_SHA,
      receipt: receipt(),
      timedOut: false,
    });
    expect(observation.status).toBe("passed");
    expect(observation.metricsById["independent-review-dispositions-complete"]).toEqual({
      id: "independent-review-dispositions-complete",
      kind: "boolean",
      value: true,
    });
  });

  it("reports incomplete for a review bound to the wrong SHA", () => {
    const observation = observeIndependentReviewV1({
      profile: parsedProfile(),
      expectedCommitSha: COMMIT_SHA,
      receipt: receipt({ commitSha: WRONG_SHA }),
      timedOut: false,
    });
    expect(observation.status).toBe("incomplete");
    expect(observation.findings[0]?.code).toBe("PROJECT_HEALTH_INDEPENDENT_REVIEW_INCOMPLETE");
  });

  it("reports incomplete when the review times out", () => {
    const observation = observeIndependentReviewV1({
      profile: parsedProfile(),
      expectedCommitSha: COMMIT_SHA,
      receipt: null,
      timedOut: true,
    });
    expect(observation.status).toBe("incomplete");
    expect(observation.findings[0]?.code).toBe("PROJECT_HEALTH_INDEPENDENT_REVIEW_INCOMPLETE");
    expect(observation.findings[0]?.policy).toBe("advisory-p2");
  });

  it("promotes a Host-confirmed AI P1 to a Blocking Finding", () => {
    const observation = observeIndependentReviewV1({
      profile: parsedProfile(),
      expectedCommitSha: COMMIT_SHA,
      receipt: receipt({
        candidateFindings: [CANDIDATE],
        dispositionsByFingerprint: { [CANDIDATE.fingerprint]: "host-confirmed" },
      }),
      timedOut: false,
    });
    expect(observation.status).toBe("failed");
    expect(observation.findings[0]?.code).toBe("PROJECT_HEALTH_INDEPENDENT_REVIEW_HOST_CONFIRMED");
    expect(observation.findings[0]?.policy).toBe("blocking-p1");
    expect(observation.metricsById["independent-review-dispositions-complete"]).toEqual({
      id: "independent-review-dispositions-complete",
      kind: "boolean",
      value: true,
    });
  });

  it("stays incomplete while a candidate is pending Host review", () => {
    const observation = observeIndependentReviewV1({
      profile: parsedProfile(),
      expectedCommitSha: COMMIT_SHA,
      receipt: receipt({
        status: "incomplete",
        candidateFindings: [CANDIDATE],
        dispositionsByFingerprint: { [CANDIDATE.fingerprint]: "pending-host-review" },
      }),
      timedOut: false,
    });
    expect(observation.status).toBe("incomplete");
    expect(observation.findings[0]?.code).toBe("PROJECT_HEALTH_INDEPENDENT_REVIEW_INCOMPLETE");
  });
});
