import {
  AnimationAction,
  AnimationClip,
  AnimationMixer,
  LoopOnce,
  LoopRepeat,
  Object3D,
} from "three";
import type {
  ActionManifest,
  ActionManifestEntry,
} from "../../contracts/src/index.js";

export interface ActionManifestIssue {
  code: "DUPLICATE_ACTION_ID" | "DUPLICATE_CLIP_NAME" | "MISSING_CLIP";
  actionId?: string;
  clip?: string;
  message: string;
}

export interface ActionPlayer {
  readonly currentActionId: string | null;
  has(actionId: string): boolean;
  play(actionId: string, options?: { restart?: boolean }): boolean;
}

export interface ActionRegistryOptions {
  root: Object3D;
  clips: readonly AnimationClip[];
  manifest: ActionManifest;
  strict?: boolean;
}

interface RegisteredAction {
  definition: ActionManifestEntry;
  action: AnimationAction;
}

export function validateActionManifest(
  clips: readonly AnimationClip[],
  manifest: ActionManifest,
): ActionManifestIssue[] {
  const issues: ActionManifestIssue[] = [];
  const clipNames = new Set<string>();
  const duplicatedClipNames = new Set<string>();
  for (const clip of clips) {
    if (clipNames.has(clip.name)) duplicatedClipNames.add(clip.name);
    clipNames.add(clip.name);
  }

  for (const clip of duplicatedClipNames) {
    issues.push({
      code: "DUPLICATE_CLIP_NAME",
      clip,
      message: `Animation source contains more than one clip named ${clip}.`,
    });
  }

  const actionIds = new Set<string>();
  for (const definition of manifest.actions) {
    if (actionIds.has(definition.id)) {
      issues.push({
        code: "DUPLICATE_ACTION_ID",
        actionId: definition.id,
        message: `Action id ${definition.id} is declared more than once.`,
      });
    }
    actionIds.add(definition.id);

    if (!clipNames.has(definition.clip)) {
      issues.push({
        code: "MISSING_CLIP",
        actionId: definition.id,
        clip: definition.clip,
        message: `Action ${definition.id} maps to missing clip ${definition.clip}.`,
      });
    }
  }
  return issues;
}

/**
 * Maps stable gameplay action ids to source-specific clip names.
 * Consumers never need to know whether an asset calls its walk clip "walk",
 * "Standard Walk", or something generated by an exporter.
 */
export class ActionRegistry implements ActionPlayer {
  readonly mixer: AnimationMixer;
  readonly manifest: ActionManifest;
  readonly issues: readonly ActionManifestIssue[];

  private readonly actions = new Map<string, RegisteredAction>();
  private activeAction: RegisteredAction | null = null;
  private activeActionId: string | null = null;

  constructor(options: ActionRegistryOptions) {
    this.manifest = options.manifest;
    this.issues = validateActionManifest(options.clips, options.manifest);
    if ((options.strict ?? true) && this.issues.length > 0) {
      throw new Error(this.issues.map((issue) => issue.message).join("\n"));
    }

    this.mixer = new AnimationMixer(options.root);
    const clipsByName = new Map(options.clips.map((clip) => [clip.name, clip]));
    for (const definition of options.manifest.actions) {
      if (this.actions.has(definition.id)) continue;
      const clip = clipsByName.get(definition.clip);
      if (clip === undefined) continue;
      const action = this.mixer.clipAction(clip);
      action.enabled = true;
      action.setEffectiveTimeScale(definition.speed);
      if (definition.loop) {
        action.setLoop(LoopRepeat, Infinity);
        action.clampWhenFinished = false;
      } else {
        action.setLoop(LoopOnce, 1);
        action.clampWhenFinished = true;
      }
      this.actions.set(definition.id, { action, definition });
    }
  }

  get currentActionId(): string | null {
    return this.activeActionId;
  }

  get supportedActionIds(): readonly string[] {
    return [...this.actions.keys()];
  }

  has(actionId: string): boolean {
    return this.actions.has(actionId);
  }

  play(actionId: string, options: { restart?: boolean } = {}): boolean {
    const next = this.actions.get(actionId);
    if (next === undefined) return false;
    if (this.activeActionId === actionId && options.restart !== true) return true;

    const previous = this.activeAction;
    if (previous !== null) {
      previous.action.fadeOut(next.definition.blendIn);
    }

    next.action
      .reset()
      .setEffectiveTimeScale(next.definition.speed)
      .fadeIn(next.definition.blendIn)
      .play();
    this.activeAction = next;
    this.activeActionId = actionId;
    return true;
  }

  update(deltaSeconds: number): void {
    if (Number.isFinite(deltaSeconds) && deltaSeconds > 0) {
      this.mixer.update(deltaSeconds);
    }
  }

  stop(fadeOutSeconds = 0): void {
    if (this.activeAction === null) return;
    if (fadeOutSeconds > 0) this.activeAction.action.fadeOut(fadeOutSeconds);
    else this.activeAction.action.stop();
    this.activeAction = null;
    this.activeActionId = null;
  }

  dispose(): void {
    this.mixer.stopAllAction();
    this.mixer.uncacheRoot(this.mixer.getRoot());
    this.actions.clear();
    this.activeAction = null;
    this.activeActionId = null;
  }
}
