import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { assertAgentSelfCheckBundleParity } from "./agent-self-check-bundle";

describe("Agent self-check bundle parity", () => {
  it("rejects generated bytes that differ from the tracked bundle", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "worldkit-bundle-parity-"));
    try {
      const generatedBundlePath = path.join(root, "generated.mjs");
      const trackedBundlePath = path.join(root, "tracked.mjs");
      await Promise.all([
        writeFile(generatedBundlePath, "generated\n"),
        writeFile(trackedBundlePath, "tracked\n"),
      ]);

      await expect(
        assertAgentSelfCheckBundleParity({
          bundleId: "planner",
          generatedBundlePath,
          trackedBundlePath,
        }),
      ).rejects.toThrow(/AGENT_SELF_CHECK_BUNDLE_STALE.*planner/);
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("accepts byte-identical generated and tracked bundles", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "worldkit-bundle-parity-"));
    try {
      const generatedBundlePath = path.join(root, "generated.mjs");
      const trackedBundlePath = path.join(root, "tracked.mjs");
      await Promise.all([
        writeFile(generatedBundlePath, "same\n"),
        writeFile(trackedBundlePath, "same\n"),
      ]);

      await expect(
        assertAgentSelfCheckBundleParity({
          bundleId: "builder",
          generatedBundlePath,
          trackedBundlePath,
        }),
      ).resolves.toBeUndefined();
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});
