export type TestLaneV1 = "contract" | "resource-heavy";

export type ResourceHeavyReasonCodeV1 =
  | "browser-or-server-process"
  | "native-havok-or-recast"
  | "measured-duration"
  | "measured-memory"
  | "measured-contention";

export interface TestGateManifestEntryV1 {
  readonly path: string;
  readonly lane: TestLaneV1;
  readonly reasonCodes?: readonly ResourceHeavyReasonCodeV1[];
}

export const TEST_GATE_MANIFEST_V1: readonly TestGateManifestEntryV1[] = Object.freeze([
  { path: "apps/native-scene-playground/src/cloud-ridge-scene.test.ts", lane: "contract" },
  { path: "apps/native-scene-playground/src/hosted-runtime-bridge.test.ts", lane: "contract" },
  { path: "apps/native-scene-playground/src/native-package-migration.test.ts", lane: "contract" },
  { path: "apps/native-scene-playground/src/native-runtime-host-module-loader.test.ts", lane: "contract" },
  { path: "apps/native-scene-playground/src/native-scene-source-clean-break.test.ts", lane: "contract" },
  { path: "apps/playground/src/artifact-renderer-lifecycle.test.ts", lane: "contract" },
  { path: "apps/playground/src/artifact-write-capability.test.ts", lane: "contract" },
  { path: "apps/playground/src/authoring-export.test.ts", lane: "contract" },
  { path: "apps/playground/src/authoring-loader.test.ts", lane: "contract" },
  { path: "apps/playground/src/babylon-artifact-renderer.test.ts", lane: "contract" },
  { path: "apps/playground/src/babylon-world-adapter.test.ts", lane: "contract" },
  { path: "apps/playground/src/canvas-recorder.test.ts", lane: "contract" },
  { path: "apps/playground/src/gameplay-babylon-runtime-coordinator.test.ts", lane: "contract" },
  { path: "apps/playground/src/gameplay-page-lifecycle.test.ts", lane: "contract" },
  { path: "apps/playground/src/mounted-skateboard-controls.test.ts", lane: "contract" },
  { path: "apps/playground/src/outdoor-scene-gameplay-loader.test.ts", lane: "resource-heavy", reasonCodes: ["browser-or-server-process"] },
  { path: "apps/playground/src/page-exit-lifecycle.test.ts", lane: "contract" },
  { path: "apps/playground/src/playground-feature-inspection.test.ts", lane: "contract" },
  { path: "apps/playground/src/playground-runtime-route.test.ts", lane: "contract" },
  { path: "apps/playground/src/recording-workbench.test.ts", lane: "contract" },
  { path: "apps/playground/src/scenes/mounted-skateboard-s1.test.ts", lane: "contract" },
  { path: "apps/playground/src/scenes/scenes.test.ts", lane: "contract" },
  { path: "apps/playground/src/subject-preset-local.test.ts", lane: "contract" },
  { path: "apps/playground/src/subject-preset-workbench.test.ts", lane: "contract" },
  { path: "apps/playground/src/worldkit-asset-resolver.test.ts", lane: "contract" },
  { path: "apps/playground/src/worldkit-authoring-capture-api.test.ts", lane: "contract" },
  { path: "apps/playground/src/worldkit-authoring-edit-add-house.browser.test.ts", lane: "resource-heavy", reasonCodes: ["browser-or-server-process"] },
  { path: "apps/playground/src/worldkit-authoring-edit-api.browser.test.ts", lane: "resource-heavy", reasonCodes: ["browser-or-server-process"] },
  { path: "apps/playground/src/worldkit-authoring-edit-api.test.ts", lane: "contract" },
  { path: "apps/playground/src/worldkit-authoring-edit-host.test.ts", lane: "contract" },
  { path: "apps/playground/src/worldkit-browser-api.test.ts", lane: "resource-heavy", reasonCodes: ["browser-or-server-process"] },
  { path: "apps/playground/src/worldkit-ready-reset.browser.test.ts", lane: "resource-heavy", reasonCodes: ["browser-or-server-process"] },
  { path: "apps/playground/vite-host.test.ts", lane: "contract" },
  { path: "packages/authoring-edit/src/authoring-edit.test.ts", lane: "contract" },
  { path: "packages/authoring-edit/src/override-policy/override-policy.test.ts", lane: "contract" },
  { path: "packages/authoring-edit/src/package-boundary.test.ts", lane: "contract" },
  { path: "packages/authoring-edit/src/schema-projection/schema-projection.test.ts", lane: "contract" },
  { path: "packages/authoring-edit/src/world-change/world-change.test.ts", lane: "contract" },
  { path: "packages/authoring-host/src/authoring-edit-host.test.ts", lane: "contract" },
  { path: "packages/authoring-host/src/journal/candidate-recovery.test.ts", lane: "contract" },
  { path: "packages/authoring-host/src/journal/journal.test.ts", lane: "contract" },
  { path: "packages/authoring-host/src/journal/publication-adversarial.test.ts", lane: "contract" },
  { path: "packages/authoring-host/src/journal/publication-recovery.test.ts", lane: "contract" },
  { path: "packages/authoring-host/src/lease-store.test.ts", lane: "contract" },
  { path: "packages/authoring-host/src/package-boundary.test.ts", lane: "contract" },
  { path: "packages/authoring-host/src/prepared-candidate.test.ts", lane: "contract" },
  { path: "packages/authoring/src/authoring-document-hash-v4.test.ts", lane: "contract" },
  { path: "packages/authoring/src/authoring-v4.test.ts", lane: "contract" },
  { path: "packages/authoring/src/authoring.test.ts", lane: "contract" },
  { path: "packages/authoring/src/layout-input.test.ts", lane: "contract" },
  { path: "packages/authoring/src/normalize-v4-clean-break.test.ts", lane: "contract" },
  { path: "packages/authoring/src/normalize-v4.test.ts", lane: "contract" },
  { path: "packages/authoring/src/normalize.test.ts", lane: "contract" },
  { path: "packages/authoring/src/scene-brief-v1.test.ts", lane: "contract" },
  { path: "packages/authoring/src/subject-definition-normalizer.test.ts", lane: "contract" },
  { path: "packages/authoring/src/subject-preset-candidate.test.ts", lane: "contract" },
  { path: "packages/authoring/src/validate-fragment-v4.test.ts", lane: "contract" },
  { path: "packages/camera/src/camera-domain-contract.test.ts", lane: "contract" },
  { path: "packages/camera/src/camera-selection.test.ts", lane: "contract" },
  { path: "packages/camera/src/package-boundary.test.ts", lane: "contract" },
  { path: "packages/character-movement/src/character-movement-runtime.test.ts", lane: "contract" },
  { path: "packages/character-movement/src/layered-move.test.ts", lane: "contract" },
  { path: "packages/character-movement/src/package-boundary.test.ts", lane: "contract" },
  { path: "packages/character-movement/src/root-motion-source.test.ts", lane: "contract" },
  { path: "packages/character-movement/src/transition-resolver.test.ts", lane: "contract" },
  { path: "packages/compiler/src/capability-compile.test.ts", lane: "contract" },
  { path: "packages/compiler/src/compile-traversal-lock.test.ts", lane: "contract" },
  { path: "packages/compiler/src/compile.test.ts", lane: "contract" },
  { path: "packages/control-capture/src/control-capture.test.ts", lane: "contract" },
  { path: "packages/gameplay-contracts/src/gameplay-artifacts.test.ts", lane: "contract" },
  { path: "packages/gameplay-contracts/src/gameplay-contracts.test.ts", lane: "contract" },
  { path: "packages/gameplay/src/core-gameplay-bootstrap.test.ts", lane: "contract" },
  { path: "packages/gameplay/src/core-semantic-action-feature.test.ts", lane: "contract" },
  { path: "packages/gameplay/src/gameplay-action-effect-registry.test.ts", lane: "contract" },
  { path: "packages/gameplay/src/gameplay-command-dispatcher.test.ts", lane: "contract" },
  { path: "packages/gameplay/src/gameplay-feature-manager.test.ts", lane: "contract" },
  { path: "packages/gameplay/src/gameplay-state.test.ts", lane: "contract" },
  { path: "packages/gameplay/src/mounted-relationship-feature.test.ts", lane: "contract" },
  { path: "packages/layout-solver/src/candidates.test.ts", lane: "contract" },
  { path: "packages/layout-solver/src/evaluators.test.ts", lane: "contract" },
  { path: "packages/layout-solver/src/geometry.test.ts", lane: "contract" },
  { path: "packages/layout-solver/src/profile-registry.test.ts", lane: "contract" },
  { path: "packages/layout-solver/src/report.test.ts", lane: "contract" },
  { path: "packages/layout-solver/src/solve.test.ts", lane: "contract" },
  { path: "packages/native-babylon-block-profile/src/api-type.test.ts", lane: "contract" },
  { path: "packages/native-babylon-block-profile/src/authoring-capture.test.ts", lane: "contract" },
  { path: "packages/native-babylon-block-profile/src/babylon-visual-adapter.test.ts", lane: "contract" },
  { path: "packages/native-babylon-block-profile/src/check.test.ts", lane: "contract" },
  { path: "packages/native-babylon-block-profile/src/collider-contribution.test.ts", lane: "contract" },
  { path: "packages/native-babylon-block-profile/src/layout.test.ts", lane: "contract" },
  { path: "packages/native-babylon-block-profile/src/package-boundary.test.ts", lane: "contract" },
  { path: "packages/native-babylon-block-profile/src/profile-settlement.test.ts", lane: "contract" },
  { path: "packages/native-babylon-block-profile/src/profile.test.ts", lane: "contract" },
  { path: "packages/native-babylon-block-profile/src/reconstruction-corpus.test.ts", lane: "contract" },
  { path: "packages/native-babylon-block-profile/src/session.test.ts", lane: "contract" },
  { path: "packages/native-babylon-block-profile/src/shapes.test.ts", lane: "contract" },
  { path: "packages/native-babylon/src/authority-audit.test.ts", lane: "contract" },
  { path: "packages/native-babylon/src/candidate-admission.test.ts", lane: "contract" },
  { path: "packages/native-babylon/src/import-profile.test.ts", lane: "contract" },
  { path: "packages/native-babylon/src/module.test.ts", lane: "contract" },
  { path: "packages/native-babylon/src/package-boundary.test.ts", lane: "contract" },
  { path: "packages/native-babylon/src/profile-settlement.test.ts", lane: "contract" },
  { path: "packages/native-babylon/src/runtime-replay.test.ts", lane: "contract" },
  { path: "packages/protocol/src/canonical-json.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/artifact-capture.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/babylon-camera-collision-query-port.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/babylon-character-body-port.conformance.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "packages/runtime-babylon/src/babylon-character-body-port.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/babylon-native-isolated-runtime-entry.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "packages/runtime-babylon/src/babylon-native-package-runtime.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/babylon-native-surface-admission.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/babylon-physics-world-query.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "packages/runtime-babylon/src/babylon-shader-bootstrap.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/camera-preview-channel.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "packages/runtime-babylon/src/camera-view-target-context.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/capability-runtime.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "packages/runtime-babylon/src/committed-render-pose.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/control-capture.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/control-profile-runtime.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/gameplay-world-adapter.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/geometry-generation-conformance.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/golden-humanoid-3c-vnext.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/golden-humanoid-presentation-context.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/motion-mode-resolver.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/p15-conformance.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "packages/runtime-babylon/src/p15-runtime-debt-repro.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "packages/runtime-babylon/src/polygon-triangulation.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/runtime-clean-break.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/runtime.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "packages/runtime-babylon/src/spring-arm-component.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/subject-animation-player-vnext.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/terrain-topology.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/traversal-implementation-identity.test.ts", lane: "contract" },
  { path: "packages/runtime-babylon/src/traversal-runtime-port.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "packages/runtime-babylon/src/traversal-runtime-support-conformance.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "packages/runtime-babylon/src/vertical-foot-support-anchor.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/babylon-native-scene-bootstrap.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/camera-parameter-contract.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/camera-view-contract.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/canonical-scene-execution-plan.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/capture-targets.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/control-feel-parameter-contract.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/native-execution-isolation.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/native-scene-asset-lock.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/native-scene-contribution.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/native-scene-dependency-lock.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/native-scene-diagnostics.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/native-scene-module-bundle.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/runtime-contracts.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/runtime-session-protocol.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/visual-reconstruction.test.ts", lane: "contract" },
  { path: "packages/runtime-contracts/src/world-runtime-bootstrap.test.ts", lane: "contract" },
  { path: "packages/runtime-framework/src/entity-component.test.ts", lane: "contract" },
  { path: "packages/runtime-host/src/character-movement-transaction.test.ts", lane: "contract" },
  { path: "packages/runtime-host/src/command-journal.test.ts", lane: "contract" },
  { path: "packages/runtime-host/src/gameplay-world-port.test.ts", lane: "contract" },
  { path: "packages/runtime-host/src/native-execution-admission.test.ts", lane: "contract" },
  { path: "packages/runtime-host/src/native-execution-budget.test.ts", lane: "contract" },
  { path: "packages/runtime-host/src/native-isolation-supervisor.test.ts", lane: "contract" },
  { path: "packages/runtime-host/src/publication-v2.test.ts", lane: "contract" },
  { path: "packages/runtime-host/src/runtime-host-lifecycle.test.ts", lane: "contract" },
  { path: "packages/runtime-host/src/runtime-host.test.ts", lane: "contract" },
  { path: "packages/runtime-host/src/test/fake-gameplay-world-adapter.test.ts", lane: "contract" },
  { path: "packages/runtime-host/src/world-session-fixed-actions.test.ts", lane: "contract" },
  { path: "packages/runtime-host/src/world-session-mounted.test.ts", lane: "contract" },
  { path: "packages/runtime-host/src/world-session.test.ts", lane: "contract" },
  { path: "packages/runtime-host/src/world-state-artifact-store.test.ts", lane: "contract" },
  { path: "packages/scene-authoring-contracts/src/package-boundary.test.ts", lane: "contract" },
  { path: "packages/scene-authoring-contracts/src/scene-authoring-contracts.test.ts", lane: "contract" },
  { path: "packages/subject-actions/src/action-presentation-registry.test.ts", lane: "contract" },
  { path: "packages/subject-actions/src/action-presentation-resolver.test.ts", lane: "contract" },
  { path: "packages/subject-actions/src/character-state-resolver.test.ts", lane: "contract" },
  { path: "packages/subject-composition/src/subject-composition.test.ts", lane: "contract" },
  { path: "packages/subject-contracts/src/subject-contracts.test.ts", lane: "contract" },
  { path: "packages/subject-registry/src/capability-registry.test.ts", lane: "contract" },
  { path: "packages/subject-registry/src/p15-admission-repro.test.ts", lane: "contract" },
  { path: "packages/subject-registry/src/selectable-control-feel.test.ts", lane: "contract" },
  { path: "packages/subject-registry/src/source-asset-inventory.test.ts", lane: "contract" },
  { path: "packages/subject-registry/src/subject-default-registry.test.ts", lane: "contract" },
  { path: "packages/subject-registry/src/subject-preset-closure.test.ts", lane: "contract" },
  { path: "packages/subject-registry/src/subject-registry.test.ts", lane: "contract" },
  { path: "packages/subject-registry/src/xier120-subjects.test.ts", lane: "contract" },
  { path: "packages/terrain-compiler/src/canonicalization/decode-png.test.ts", lane: "contract" },
  { path: "packages/terrain-compiler/src/canonicalization/project-signed-rgb.test.ts", lane: "contract" },
  { path: "packages/terrain-compiler/src/canonicalization/summarize-projection.test.ts", lane: "contract" },
  { path: "packages/terrain-compiler/src/cli/main.test.ts", lane: "contract" },
  { path: "packages/terrain-compiler/src/compile-terrain-height-intent.test.ts", lane: "contract" },
  { path: "packages/terrain-compiler/src/constraints/apply-terrain-constraints.test.ts", lane: "contract" },
  { path: "packages/terrain-compiler/src/constraints/derive-authoring-constraints.test.ts", lane: "contract" },
  { path: "packages/terrain-compiler/src/exemplar-manifest.test.ts", lane: "contract" },
  { path: "packages/terrain-compiler/src/index.test.ts", lane: "contract" },
  { path: "packages/terrain-compiler/src/raster/map-height-meters.test.ts", lane: "contract" },
  { path: "packages/terrain-compiler/src/raster/normalize-signed-height-raster.test.ts", lane: "contract" },
  { path: "packages/terrain-compiler/src/raster/prefilter-scalar-raster.test.ts", lane: "contract" },
  { path: "packages/terrain-compiler/src/raster/quantize-height-samples.test.ts", lane: "contract" },
  { path: "packages/terrain-compiler/src/raster/resample-scalar-raster.test.ts", lane: "contract" },
  { path: "packages/terrain-surface/src/orientation-xz.test.ts", lane: "contract" },
  { path: "packages/terrain-surface/src/simple-polygon-xz.test.ts", lane: "contract" },
  { path: "packages/terrain-surface/src/spawn-safety.test.ts", lane: "contract" },
  { path: "packages/terrain-surface/src/static-collider-triangle-mesh.test.ts", lane: "contract" },
  { path: "packages/terrain-surface/src/terrain-surface.test.ts", lane: "contract" },
  { path: "packages/terrain-surface/src/traversal-surface-query.test.ts", lane: "contract" },
  { path: "packages/terrain-surface/src/triangle-heightfield.test.ts", lane: "contract" },
  { path: "packages/terrain-surface/src/triangle-xz-broadphase.test.ts", lane: "contract" },
  { path: "packages/testkit/src/testkit.test.ts", lane: "contract" },
  { path: "packages/traversal-recast/src/adapter-identity.test.ts", lane: "contract" },
  { path: "packages/traversal-recast/src/build-graph.test.ts", lane: "contract" },
  { path: "packages/traversal-recast/src/build-rejection-graph.test.ts", lane: "contract" },
  { path: "packages/traversal-recast/src/evaluate-route.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "packages/traversal-recast/src/evaluate-route.v2.test.ts", lane: "contract" },
  { path: "packages/traversal-recast/src/hard-ribbon-proof.test.ts", lane: "contract" },
  { path: "packages/traversal-recast/src/heightfield-source.test.ts", lane: "contract" },
  { path: "packages/traversal-recast/src/provider-acceptance.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "packages/traversal-recast/src/provider-lifecycle.test.ts", lane: "contract" },
  { path: "packages/traversal-recast/src/provider-patch-identity.test.ts", lane: "contract" },
  { path: "packages/traversal-recast/src/public-boundary.test.ts", lane: "contract" },
  { path: "packages/traversal-recast/src/query-provider.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "packages/traversal-recast/src/query-route.test.ts", lane: "contract" },
  { path: "packages/traversal-recast/src/recast-config.test.ts", lane: "contract" },
  { path: "packages/traversal-recast/src/route-rejection-proof.test.ts", lane: "contract" },
  { path: "packages/traversal/src/build-budget.test.ts", lane: "contract" },
  { path: "packages/traversal/src/build-input.test.ts", lane: "contract" },
  { path: "packages/traversal/src/build-input.v2.test.ts", lane: "contract" },
  { path: "packages/traversal/src/capability-envelope.test.ts", lane: "contract" },
  { path: "packages/traversal/src/collider-subshape-id.test.ts", lane: "contract" },
  { path: "packages/traversal/src/connectivity-result.test.ts", lane: "contract" },
  { path: "packages/traversal/src/graph-contract.test.ts", lane: "contract" },
  { path: "packages/traversal/src/lock.test.ts", lane: "contract" },
  { path: "packages/traversal/src/path-receipt.test.ts", lane: "contract" },
  { path: "packages/traversal/src/profile-registry.test.ts", lane: "contract" },
  { path: "packages/traversal/src/route-overlay.test.ts", lane: "contract" },
  { path: "packages/traversal/src/route-v2-contracts.test.ts", lane: "contract" },
  { path: "packages/traversal/src/runtime-evidence.test.ts", lane: "contract" },
  { path: "packages/traversal/src/runtime-probe-contract.test.ts", lane: "contract" },
  { path: "packages/validation/src/route-evaluator.test.ts", lane: "contract" },
  { path: "packages/validation/src/route-evidence-publication.test.ts", lane: "contract" },
  { path: "packages/validation/src/route-runtime-probe.test.ts", lane: "contract" },
  { path: "packages/validation/src/route-validation-set.test.ts", lane: "contract" },
  { path: "packages/validation/src/route.test.ts", lane: "contract" },
  { path: "packages/validation/src/validation.test.ts", lane: "contract" },
  { path: "packages/validation/src/world-package-validation-subject.test.ts", lane: "contract" },
  { path: "packages/world-identity/src/package-boundary.test.ts", lane: "contract" },
  { path: "packages/world-identity/src/world-build-identity.test.ts", lane: "contract" },
  { path: "packages/world-package/src/package-build.test.ts", lane: "resource-heavy", reasonCodes: ["measured-duration"] },
  { path: "packages/world-package/src/package-contract.test.ts", lane: "contract" },
  { path: "packages/world-package/src/package-directory.test.ts", lane: "contract" },
  { path: "packages/world-package/src/store.test.ts", lane: "contract" },
  { path: "packages/world/src/authoring-workflow.test.ts", lane: "contract" },
  { path: "packages/world/src/canonical-route-projection.test.ts", lane: "contract" },
  { path: "packages/world/src/features.test.ts", lane: "contract" },
  { path: "packages/world/src/landmarks.test.ts", lane: "contract" },
  { path: "packages/world/src/planning-artifacts.test.ts", lane: "contract" },
  { path: "packages/world/src/random.test.ts", lane: "contract" },
  { path: "packages/world/src/scene.test.ts", lane: "contract" },
  { path: "packages/world/src/schema.test.ts", lane: "contract" },
  { path: "packages/world/src/shapes.test.ts", lane: "contract" },
  { path: "packages/world/src/terrain.test.ts", lane: "contract" },
  { path: "packages/world/src/world-spec.test.ts", lane: "contract" },
  { path: "scripts/agents/agent-planner-self-check.test.ts", lane: "resource-heavy", reasonCodes: ["measured-duration"] },
  { path: "scripts/agents/agent-self-check.test.ts", lane: "resource-heavy", reasonCodes: ["measured-duration"] },
  { path: "scripts/agents/builder-skill.test.ts", lane: "contract" },
  { path: "scripts/agents/native-block-builder-skill.test.ts", lane: "contract" },
  { path: "scripts/agents/planner-skill.test.ts", lane: "contract" },
  { path: "scripts/assets/modular-subject-runtime-bundles.test.ts", lane: "contract" },
  { path: "scripts/assets/modular-subject-source-packages.test.ts", lane: "resource-heavy", reasonCodes: ["measured-duration"] },
  { path: "scripts/cli/runtime-session.integration.test.ts", lane: "resource-heavy", reasonCodes: ["browser-or-server-process", "native-havok-or-recast"] },
  { path: "scripts/cli/worldkit-native.integration.test.ts", lane: "resource-heavy", reasonCodes: ["measured-duration"] },
  { path: "scripts/cli/worldkit-route-run.integration.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "scripts/cli/worldkit.test.ts", lane: "contract" },
  { path: "scripts/fixtures/generate-golden-humanoid-glb.test.ts", lane: "contract" },
  { path: "scripts/lib/agent-self-check-bundle.test.ts", lane: "contract" },
  { path: "scripts/lib/ai-schema-provider-conformance.test.ts", lane: "contract" },
  { path: "scripts/lib/artifact-directory-promotion.test.ts", lane: "contract" },
  { path: "scripts/lib/authoring-edit-cli.test.ts", lane: "contract" },
  { path: "scripts/lib/authoring-edit-full-reload.integration.test.ts", lane: "contract" },
  { path: "scripts/lib/authoring-edit-host-bridge.test.ts", lane: "contract" },
  { path: "scripts/lib/builder-large-world-evidence.test.ts", lane: "contract" },
  { path: "scripts/lib/composition-gate.test.ts", lane: "contract" },
  { path: "scripts/lib/control-capture-bundle.test.ts", lane: "contract" },
  { path: "scripts/lib/control-capture-validation.test.ts", lane: "contract" },
  { path: "scripts/lib/durable-authoring-edit-host.integration.test.ts", lane: "resource-heavy", reasonCodes: ["browser-or-server-process"] },
  { path: "scripts/lib/durable-authoring-edit-host.test.ts", lane: "contract" },
  { path: "scripts/lib/durable-world-change-runtime.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "scripts/lib/example-take-world-identity.test.ts", lane: "contract" },
  { path: "scripts/lib/exclusive-evidence-publication.test.ts", lane: "contract" },
  { path: "scripts/lib/file-world-package.test.ts", lane: "contract" },
  { path: "scripts/lib/g-bot-evidence.test.ts", lane: "contract" },
  { path: "scripts/lib/glb-admission.test.ts", lane: "resource-heavy", reasonCodes: ["measured-memory"] },
  { path: "scripts/lib/headless-runtime-session.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "scripts/lib/independent-test-gate.test.ts", lane: "contract" },
  { path: "scripts/lib/layout-artifacts.test.ts", lane: "contract" },
  { path: "scripts/lib/modular-subject-runtime-bundle.test.ts", lane: "contract" },
  { path: "scripts/lib/modular-subject-source.test.ts", lane: "contract" },
  { path: "scripts/lib/plan-lock.test.ts", lane: "contract" },
  { path: "scripts/lib/product-asset-evidence.test.ts", lane: "contract" },
  { path: "scripts/lib/product-asset-intake.test.ts", lane: "contract" },
  { path: "scripts/lib/route-runtime-probe.integration.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "scripts/lib/route-validation-cli.test.ts", lane: "contract" },
  { path: "scripts/lib/route-validation-orchestrator.test.ts", lane: "resource-heavy", reasonCodes: ["measured-duration"] },
  { path: "scripts/lib/route-validation-runner.test.ts", lane: "resource-heavy", reasonCodes: ["measured-duration"] },
  { path: "scripts/lib/runtime-session-executor.test.ts", lane: "contract" },
  { path: "scripts/lib/runtime-session-ndjson.test.ts", lane: "contract" },
  { path: "scripts/lib/runtime-session-wal.test.ts", lane: "contract" },
  { path: "scripts/lib/simulation-take-cli.test.ts", lane: "contract" },
  { path: "scripts/lib/simulation-take-runner.test.ts", lane: "contract" },
  { path: "scripts/lib/subject-pose-evidence.test.ts", lane: "contract" },
  { path: "scripts/lib/subject-preset-promotion.test.ts", lane: "contract" },
  { path: "scripts/lib/subject-source-migration-audit.test.ts", lane: "contract" },
  { path: "scripts/lib/test-gate-census.test.ts", lane: "contract" },
  { path: "scripts/lib/transactional-artifact-promotion.test.ts", lane: "contract" },
  { path: "scripts/lib/traversal-area-runtime-collision.integration.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "scripts/lib/validation-cli.test.ts", lane: "contract" },
  { path: "scripts/lib/workspace-boundary-contract.test.ts", lane: "contract" },
  { path: "scripts/lib/world-change-publication-recovery.test.ts", lane: "contract" },
  { path: "scripts/lib/world-package-cli.test.ts", lane: "contract" },
  { path: "scripts/lib/world-package-resource-resolver.test.ts", lane: "contract" },
  { path: "scripts/lib/world-package-signing.test.ts", lane: "contract" },
  { path: "scripts/lib/worldkit-server.test.ts", lane: "resource-heavy", reasonCodes: ["browser-or-server-process"] },
  { path: "scripts/lib/worldkit-source-commit.test.ts", lane: "contract" },
  { path: "scripts/native-scene/asset-lock.test.ts", lane: "contract" },
  { path: "scripts/native-scene/authoring-workspace.test.ts", lane: "contract" },
  { path: "scripts/native-scene/check-policy.test.ts", lane: "contract" },
  { path: "scripts/native-scene/dependency-lock.test.ts", lane: "contract" },
  { path: "scripts/native-scene/explain.test.ts", lane: "contract" },
  { path: "scripts/native-scene/hosted/container-provider.test.ts", lane: "contract" },
  { path: "scripts/native-scene/hosted/hostile-fixtures/cpu.test.ts", lane: "contract" },
  { path: "scripts/native-scene/hosted/runner-distribution.test.ts", lane: "contract" },
  { path: "scripts/native-scene/hosted/runtime-usage-frame.test.ts", lane: "contract" },
  { path: "scripts/native-scene/module-bundle.test.ts", lane: "resource-heavy", reasonCodes: ["measured-duration"] },
  { path: "scripts/native-scene/native-package-input.test.ts", lane: "resource-heavy", reasonCodes: ["measured-duration"] },
  { path: "scripts/native-scene/native-scene-check.test.ts", lane: "resource-heavy", reasonCodes: ["measured-duration"] },
  { path: "scripts/native-scene/source-admission.test.ts", lane: "contract" },
  { path: "scripts/project-health/change-impact.test.ts", lane: "contract" },
  { path: "scripts/project-health/cli.test.ts", lane: "contract" },
  { path: "scripts/project-health/contracts.test.ts", lane: "contract" },
  { path: "scripts/project-health/dependency-inventory.test.ts", lane: "contract" },
  { path: "scripts/project-health/evidence-store.test.ts", lane: "contract" },
  { path: "scripts/project-health/mode-observer.test.ts", lane: "contract" },
  { path: "scripts/project-health/process-runner.test.ts", lane: "contract" },
  { path: "scripts/project-health/registry.test.ts", lane: "contract" },
  { path: "scripts/project-health/report.test.ts", lane: "contract" },
  { path: "scripts/project-health/runtime-probe-registry.test.ts", lane: "contract" },
  { path: "scripts/project-health/sensors/contract-parity.test.ts", lane: "contract" },
  { path: "scripts/project-health/sensors/documentation-truth.test.ts", lane: "contract" },
  { path: "scripts/project-health/sensors/independent-review.test.ts", lane: "contract" },
  { path: "scripts/project-health/sensors/performance-size.test.ts", lane: "contract" },
  { path: "scripts/project-health/sensors/runtime-health.test.ts", lane: "contract" },
  { path: "scripts/project-health/sensors/supplemental-authority.test.ts", lane: "contract" },
  { path: "scripts/project-health/sensors/supply-chain.test.ts", lane: "contract" },
  { path: "scripts/project-health/sensors/test-topology.test.ts", lane: "contract" },
  { path: "scripts/project-health/sensors/visual-evidence.test.ts", lane: "contract" },
  { path: "scripts/project-health/sensors/workspace-boundary.test.ts", lane: "contract" },
  { path: "scripts/project-health/workspace-boundary-adapter.test.ts", lane: "contract" },
  { path: "scripts/scenes/finalize-scene-terrain.test.ts", lane: "contract" },
  { path: "scripts/scenes/finalize-spatial-build.test.ts", lane: "contract" },
  { path: "scripts/scenes/record-scene-authoring-attempt.test.ts", lane: "contract" },
  { path: "scripts/testing/repository-layout.test.ts", lane: "contract" },
  { path: "scripts/testing/workspace-boundary.test.ts", lane: "contract" },
  { path: "scripts/verification/bwb3-block-capture-evidence.test.ts", lane: "contract" },
  { path: "scripts/verification/bwb4-block-collider-runtime.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "scripts/verification/bwb5-block-reconstruction-corpus.test.ts", lane: "resource-heavy", reasonCodes: ["native-havok-or-recast"] },
  { path: "scripts/verification/hosted-native-isolation-evidence.test.ts", lane: "contract" },
  { path: "scripts/verification/locomotion-capability-state.test.ts", lane: "contract" },
  { path: "scripts/verification/verification-browser-launch.test.ts", lane: "contract" },
  { path: "scripts/verification/verify-3c-migration.test.ts", lane: "contract" },
  { path: "scripts/verification/verify-bna1-clean-break.test.ts", lane: "contract" },
  { path: "scripts/verification/verify-bna2-clean-break.test.ts", lane: "contract" },
  { path: "scripts/verification/verify-bna5-clean-break.test.ts", lane: "contract" },
  { path: "scripts/verification/verify-outdoor-gameplay-worlds.test.ts", lane: "contract" },
  { path: "scripts/verification/verify-placement-layout.test.ts", lane: "contract" },
  { path: "scripts/verification/verify-route-r0-contract.test.ts", lane: "contract" },
  { path: "scripts/verification/verify-route-r1-heightfield.test.ts", lane: "contract" },
  { path: "scripts/verification/verify-route-r1b-static-platform.test.ts", lane: "contract" },
  { path: "scripts/verification/verify-runtime-authority-boundaries.test.ts", lane: "contract" },
  { path: "scripts/verification/verify-unreleased-clean-break.test.ts", lane: "contract" },
  { path: "scripts/verification/verify-xier120-subjects.test.ts", lane: "contract" },
  { path: "scripts/visual/composition-lifecycle.test.ts", lane: "contract" },
  { path: "scripts/visual/entry-third-person.test.ts", lane: "contract" },
  { path: "scripts/visual/gemini-visual-pipeline.test.ts", lane: "contract" },
  { path: "scripts/visual/visual-reconstruction.test.ts", lane: "contract" },
]);
