import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {ROOT,read,write,sha256,glbInfo} from './core.mjs';
import {build,validateFormats} from './library.mjs';
const args=process.argv.slice(2),opt=k=>args.includes(k)?args[args.indexOf(k)+1]:null;
const require=createRequire(import.meta.url),validator=require('./vendor/gltf-validator/index.js');
async function main(){
 const input=opt('--input'),id=opt('--id'),group=opt('--group'),name=opt('--name'),version=opt('--version')||'0.1.0';
 if(!input||!id||!group||!name)throw Error('Required: --input model.glb --id stable.id --group animals --name Name [--version 0.1.0]');
 if(!/^[a-z][a-z0-9._-]*$/.test(id)||!/^\d+\.\d+\.\d+$/.test(version)||!['characters','animals','vehicles','robots','fantastical','objects'].includes(group))throw Error('INVALID_ID_VERSION_OR_GROUP');
 const base=`subjects/${group}/${id}/${version}`,dir=path.join(ROOT,base);if(fs.existsSync(dir))throw Error('IMMUTABLE_VERSION_EXISTS: choose a new version');
 const bytes=fs.readFileSync(input),info=glbInfo(input);if(info.external_uris.length)throw Error('GLB_MUST_BE_SELF_CONTAINED');
 const format=await validator.validateBytes(new Uint8Array(bytes),{uri:path.basename(input),maxIssues:100});if(format.issues.numErrors)throw Error('GLTF_VALIDATION_FAILED: '+format.issues.numErrors+' errors. Source was not registered.');
 const model=`${base}/model/model.glb`,file={path:model,sha256:sha256(bytes),byte_length:bytes.length,format:'glb',role:'model',source_path:path.basename(input),reused_by:[id]};
 const asset={schema_version:'1.0',asset_id:id,asset_version:version,display_name:name,aliases:[name],browse_group:group,semantic_type:group+'.unclassified',semantic_subtypes:[],morphology:{architecture:info.skins?'skinned_articulated':'rigid_single',profiles:[],appendages:[],stance:'unknown'},scale:{units:'meter',up_axis:'Y',forward_axis:'unknown',dimensions_m:null,source_transform:null},lifecycle:'assets_ready',placeholder:false,description:'新入库资源；分类、骨骼语义与运行能力待标定。',default_assembly:`${base}/assemblies/default.json`,dependencies:[]};
 const values={'asset.json':asset,'capabilities.json':{schema_version:'1.0',movement_modes:[],movement_transitions:[],control:{archetype:'unknown',stage:'planned',profile:null},interactions:[],limitations:['尚未接入宿主控制器。']},'resources.json':{schema_version:'1.0',model,preview:null,files:[file],inspection:info,animations:info.clips.map(c=>({...c,resource:model,format:'glb',binding_status:'embedded'}))},'provenance.json':{schema_version:'1.0',source_type:'provided_export',source_url:opt('--source-url'),license:{status:'unknown',commercial_use:'unknown',redistribution:'unknown',editable_distribution:'unknown',user_export:'unknown'},license_files:[],source_hash:file.sha256,conversion_pipeline:null},'bindings/rig.json':{schema_version:'1.0',bones:info.bones,semantic_bones:{},mapping_status:'unmapped'},'bindings/animation_map.json':{schema_version:'1.0',slots:{}},'bindings/sockets.json':{schema_version:'1.0',sockets:[]},'profiles/locomotion.json':{schema_version:'1.0',parameters:{},runtime_contract:'host-supplied'},'profiles/camera.json':{schema_version:'1.0',runtime_contract:'external',runtime_requirements:[{runtime_id:'@worldkit/three',contract:'world-camera@1'}]},'collision/collision.json':{schema_version:'1.0',shapes:[],verification:'not_run'},'assemblies/default.json':{schema_version:'1.0',assembly_id:'assembly.'+id,subject:{asset_id:id,version},model,bindings:{rig:`${base}/bindings/rig.json`,animations:`${base}/bindings/animation_map.json`,sockets:`${base}/bindings/sockets.json`},profiles:{control:`${base}/profiles/locomotion.json`,camera:`${base}/profiles/camera.json`},modules:[{asset_id:'module.host.subject',version:'1.0.0'}],authority:{root_transform:'host.motor',animation:'host.animation',camera:'host.camera'},stage:'assets_ready',runtime_ready:false},'validation/latest.json':{schema_version:'1.0',structure:'pending',format:'pending',visual:'not_run',runtime:'not_run',checked_at:null,evidence:[]}};
 write(path.join(ROOT,model),bytes);for(const [p,v]of Object.entries(values))write(path.join(dir,p),v);
 for(const name of ['model','textures','animations','audio','collision','bindings','profiles','assemblies','preview','validation'])write(path.join(dir,name,'README.md'),`# ${name}\n\n属于 ${id} @ ${version}。缺失内容不代表已经支持。\n`);
 write(path.join(dir,'README.md'),`# ${name}\n\n稳定 ID: ${id} @ ${version}\n\n查看 asset.json、capabilities.json、resources.json 和 validation/latest.json。先补语义和绑定，再做宿主接入。\n`);
 const formats=args.includes('--defer-validation')?{passed:null,status:'pending'}:await validateFormats(ROOT);build(ROOT);console.log(JSON.stringify({id,version,path:base,format:formats,search_command:'node tools/library.mjs search '+id}));if(formats.passed===false)process.exitCode=1;
}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
