import path from 'node:path';
import {ROOT,read,write} from './core.mjs';
const out=(p,v)=>write(path.join(ROOT,p),v);
const taxonomies={
 subject_types:{browse_group:{characters:'人物',animals:'动物',vehicles:'载具',robots:'机器人',fantastical:'幻想生物',objects:'物件'}},
 morphology:{architecture:['skinned_articulated','rigid_articulated','rigid_single','soft_body','composite','swarm','unknown'],profiles:['biped','quadruped','hexapod','octopod','serpentine','two_wheel','four_wheel','multi_wheel','tracked','winged','finned','rotorcraft'],appendage_roles:['leg','arm','hand','foot','wing','fin','tail','neck','head','jaw','wheel','track','rotor','propeller','thruster','tentacle','manipulator','tool_mount'],stance:['upright','forward_leaning','horizontal','low_profile','suspended','floating','variable','unknown']},
 movement:{environment:['ground','wall','ceiling','water_surface','underwater','air','space','underground','rail','path_constrained'],support:['foot_contact','body_contact','wheel_contact','track_contact','buoyancy','aerodynamic_lift','rotor_lift','adhesion','suspension','path_constraint','none','ballistic'],propulsion:['legged_step','hopping','wheel_drive','track_drive','body_undulation','paddling','fin_oscillation','flapping','propeller','rotor','jet','thruster','sail','gravity','external_force'],degrees_of_freedom:['path_1d','surface_2d','planar_2d_yaw','full_3d'],gaits:['idle','walk','trot','pace','canter','run','gallop','sprint','crawl'],transitions:['start','stop','takeoff','land','enter_water','exit_water','surface','dive','attach_surface','detach_surface','enter_rail','leave_rail']},
 control:{archetype:['directional','throttle_steer','differential_drive','bike_balance','aircraft','rotorcraft','marine_3d','space_6dof','path_speed_control','target_position','unknown']},
 interaction:{actions:['pick_up','hold','drop','throw','push','pull','carry','be_carried','equip','be_equipped','weapon_use','tool_use','mount','be_mounted','drive','be_driven','ride','be_ridden','passenger','tow','be_towed','climb','be_climbed']},
 animation_semantics:{slots:['idle','walk','run','jump_start','airborne','land','attack','hit','death','takeoff','flight','swim'],root_motion:['unknown','in_place','root_translation','root_rotation']},
 lifecycle_status:{subject:['placeholder','assets_ready','deprecated'],capability:['planned','assets_ready','integrated','verified','deprecated'],validation:['pending','passed','failed','not_run','preview_loaded','verified','not_applicable','fbx_source_unvalidated']}
};
for(const [k,v]of Object.entries(taxonomies))out(`taxonomy/${k}.json`,{schema_version:'1.0',...v});
const str={type:'string'},nullable={type:['string','null']},arr=items=>({type:'array',items}),en=values=>({type:'string',enum:values}),obj=(properties,required=Object.keys(properties),extra=false)=>({type:'object',properties,required,additionalProperties:extra});
const version={type:'string',pattern:'^\\d+\\.\\d+\\.\\d+$'},id={type:'string',pattern:'^[a-z][a-z0-9._-]*$'};
const schema=(title,body)=>out(`schemas/${title}.schema.json`,{$schema:'http://json-schema.org/draft-07/schema#',title,...body});
schema('subject',obj({schema_version:{const:'1.0'},asset_id:id,asset_version:version,display_name:str,aliases:arr(str),browse_group:en(Object.keys(taxonomies.subject_types.browse_group)),semantic_type:str,semantic_subtypes:arr(str),morphology:obj({architecture:en(taxonomies.morphology.architecture),profiles:arr(en(taxonomies.morphology.profiles)),appendages:arr(obj({role:en(taxonomies.morphology.appendage_roles),count:{type:'integer',minimum:0}})),stance:en(taxonomies.morphology.stance)}),scale:obj({units:en(['meter','unknown']),up_axis:en(['Y','Z','unknown']),forward_axis:str,dimensions_m:{type:['object','null']},source_transform:{type:['object','null']}}),lifecycle:en(taxonomies.lifecycle_status.subject),placeholder:{type:'boolean'},description:str,default_assembly:str,dependencies:arr(obj({asset_id:id,version}))}));
const mode=obj({id,environment:en(taxonomies.movement.environment),support:en(taxonomies.movement.support),propulsion:en(taxonomies.movement.propulsion),degrees_of_freedom:en(taxonomies.movement.degrees_of_freedom),gaits:arr(en(taxonomies.movement.gaits)),control_archetype:en(taxonomies.control.archetype),stage:en(taxonomies.lifecycle_status.capability)});
schema('capabilities',obj({schema_version:{const:'1.0'},movement_modes:arr(mode),movement_transitions:arr(obj({from:str,to:str,transition:en(taxonomies.movement.transitions),stage:en(taxonomies.lifecycle_status.capability)})),control:obj({archetype:en(taxonomies.control.archetype),stage:en(taxonomies.lifecycle_status.capability),profile:nullable}),interactions:arr(obj({action:en(taxonomies.interaction.actions),stage:en(taxonomies.lifecycle_status.capability),contract:nullable})),limitations:arr(str)}));
const file=obj({path:str,sha256:{type:'string',pattern:'^[a-f0-9]{64}$'},byte_length:{type:'integer',minimum:0},format:str,role:str,source_path:str,reused_by:arr(str)});
file.properties.logical_paths={type:'array',uniqueItems:true,items:str,description:'Stable SDK resource identifiers mapped to this file; never disk paths.'};
schema('resources',obj({schema_version:{const:'1.0'},model:nullable,preview:nullable,files:arr(file),inspection:{type:['object','null']},animations:arr(obj({name:str,index:{type:'integer',minimum:0},duration_seconds:{type:'number',minimum:0},channels:{type:'integer',minimum:0},resource:str,format:en(['glb','three-clip-json','fbx']),loop:{type:['boolean','null']},root_motion:str,binding_status:str}))}));
// Adapter logical identifiers are optional; ordinary subjects need no Whitebox binding.
const resourcesSchemaPath=path.join(ROOT,'schemas/resources.schema.json');
const resourcesSchema=read(resourcesSchemaPath);
resourcesSchema.properties.model_logical_path={type:'string',description:'Stable SDK model identifier; not a library file path.'};
write(resourcesSchemaPath,resourcesSchema);
schema('provenance',obj({schema_version:{const:'1.0'},source_type:str,license:obj({status:str,commercial_use:str,redistribution:str,editable_distribution:str,user_export:str}),license_files:arr(str)},['schema_version','source_type','license','license_files'],true));
schema('assembly',obj({schema_version:{const:'1.0'},assembly_id:id,subject:obj({asset_id:id,version}),model:nullable,bindings:obj({rig:str,animations:str,sockets:str}),profiles:obj({control:str,camera:str}),modules:arr(obj({asset_id:id,version})),authority:obj({root_transform:str,animation:str,camera:str}),stage:en(taxonomies.lifecycle_status.capability),runtime_ready:{type:'boolean'}}));
schema('validation',obj({schema_version:{const:'1.0'},structure:en(['pending','passed','failed']),format:en(['pending','passed','failed','not_applicable','fbx_source_unvalidated']),visual:en(['not_run','preview_loaded','verified']),runtime:en(['not_run','failed','verified']),checked_at:nullable,evidence:arr(str)},['schema_version','structure','format','visual','runtime','checked_at','evidence'],true));
console.log('7 taxonomies + 6 schemas created');
