import {beforeAll,it,expect} from 'vitest';
import {Vector3} from 'three';
import {EnvironmentQueries,initEnvironmentQueries} from './environment/queries';
import {createVehicle,emptyInput,stepVehicle,type Input} from './simulation';
import {SPECS} from '@worldkit/preset-content/config';
import {getMap} from '@worldkit/preset-content/environment/maps';
beforeAll(initEnvironmentQueries);
function fixture(){const q=new EnvironmentQueries(getMap('aircraft-training')),v=createVehicle({...SPECS.find(s=>s.id==='plane')!,spawn:[0,0,0]});const step=(input:Partial<Input>,n:number)=>{for(let i=0;i<n;i++){stepVehicle(v,{...emptyInput(),...input},1/60,i/60,q);q.stepPhysics(1/60);}};return {q,v,step};}
it('rests on three spring contacts and brakes after landing',()=>{const {q,v,step}=fixture();try{step({},300);expect(v.grounded).toBe(true);expect(v.motion.aircraft!.wheels.filter(w=>w.load>100).length).toBe(3);expect(v.velocity.length()).toBeLessThan(.1);v.position.y=2;v.velocity.set(0,-2,12);step({slow:true},1200);expect(v.grounded).toBe(true);expect(v.velocity.length()).toBeLessThan(.3);expect(v.position.y).toBeGreaterThan(-.15);}finally{q.dispose();}});
it('takes off and turns through torque without teleporting orientation',()=>{const {q,v,step}=fixture();try{step({boost:true},300);expect(v.speed).toBeGreaterThan(22);const before=v.rotation.clone();step({forward:-.5},1);expect(before.angleTo(v.rotation)).toBeLessThan(.03);step({forward:-.5},360);expect(v.grounded).toBe(false);expect(v.position.y).toBeGreaterThan(5);step({steer:1},180);expect(v.roll).toBeGreaterThan(.15);step({},180);expect(Math.abs(v.roll)).toBeLessThan(.15);}finally{q.dispose();}});
it('keeps velocity independent from heading and resets angular state',()=>{const {q,v,step}=fixture();try{v.position.y=100;v.velocity.set(8,0,35);step({steer:1},1);expect(v.velocity.x).toBeGreaterThan(7);expect(createVehicle(v.spec).motion.aircraft!.angularVelocity.length()).toBe(0);}finally{q.dispose();}});
it('collides with a wall at cruise speed',()=>{const initial=fixture(),v=initial.v;initial.q.dispose();const q=new EnvironmentQueries({...getMap('aircraft-training'),boxes:[{id:'wall',position:[0,20,15],size:[100,40,1]}]});try{v.position.set(0,10,0);v.velocity.set(0,0,55);for(let i=0;i<60;i++){stepVehicle(v,emptyInput(),1/60,0,q);q.stepPhysics(1/60);}expect(v.position.z).toBeLessThan(15);}finally{q.dispose();}});

it('responds to asymmetric wheel support rather than flattening the whole aircraft',()=>{const f=fixture();f.q.dispose();const q=new EnvironmentQueries({...getMap('aircraft-training'),boxes:[...getMap('aircraft-training').boxes,{id:'bump',position:[1.1,.05,0],size:[.7,.1,.8]}]});try{for(let i=0;i<300;i++){stepVehicle(f.v,{...emptyInput(),brake:true},1/60,0,q);q.stepPhysics(1/60);}expect(Math.abs(f.v.roll)).toBeGreaterThan(.015);expect(Math.abs(f.v.roll)).toBeLessThan(.15);expect(f.v.motion.aircraft!.wheels.filter(w=>w.load>0).length).toBe(3);}finally{q.dispose();}});
it('limits suspension travel in a hard vertical landing',()=>{const {q,v,step}=fixture();try{v.position.y=1;v.velocity.y=-7;step({brake:true},120);expect(v.motion.aircraft!.hardLanding).toBe(true);expect(v.position.y).toBeGreaterThan(-.2);for(const wheel of v.motion.aircraft!.wheels)expect(Math.abs(wheel.compression)).toBeLessThanOrEqual(.18);}finally{q.dispose();}});
it('is repeatable at fixed input and close between 60 and 120 Hz',()=>{const run=(h:number)=>{const {q,v}=fixture();try{v.position.y=100;v.velocity.z=35;v.grounded=false;for(let n=0;n<6/h;n++){stepVehicle(v,{...emptyInput(),steer:.3},h,0,q);q.stepPhysics(h);}return v.position.clone();}finally{q.dispose();}};const a=run(1/60),b=run(1/60),c=run(1/120);expect(a.distanceTo(b)).toBe(0);expect(a.distanceTo(c)).toBeLessThan(.1);});
it('turns both ways within eight seconds without large altitude loss and responds to reversal',()=>{for(const direction of [-1,1])for(const speed of [35,45,58]){const {q,v,step}=fixture();try{v.position.set(0,200,0);v.velocity.set(0,0,speed);v.grounded=false;for(let n=0;n<300;n++)step({boost:v.speed<speed,slow:v.speed>speed+1},1);const start=v.position.clone(),heading=Math.atan2(v.velocity.x,v.velocity.z);let seconds=0;for(;seconds<20;seconds+=1/60){step({steer:direction,boost:v.speed<speed,slow:v.speed>speed+1},1);if(Math.abs(Math.atan2(Math.sin(Math.atan2(v.velocity.x,v.velocity.z)-heading),Math.cos(Math.atan2(v.velocity.x,v.velocity.z)-heading)))>=Math.PI/2)break;}expect(seconds).toBeLessThan(8);expect(Math.abs(v.position.y-start.y)).toBeLessThan(8);expect(v.roll*direction).toBeGreaterThan(.5);step({steer:-direction},120);expect(v.roll*direction).toBeLessThan(-.25);step({},180);expect(Math.abs(v.roll)).toBeLessThan(.12); }finally{q.dispose();}}});
