import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {launchChromiumWithSystemFallback} from '@worldkit/browser-capture/browser';
const output=process.argv[3]??'output/playwright/camera-quality/ui';await mkdir(output,{recursive:true});
const original=await readFile('apps/sdk-playground/config/camera.json','utf8');
const browser=await launchChromiumWithSystemFallback(),page=await browser.newPage({viewport:{width:1600,height:1000}}),errors:string[]=[];
page.on('pageerror',error=>errors.push(error.message));
const inspect=()=>page.evaluate(()=>window.__WORLDKIT_EVAL__!.inspectCamera!());
try {
 await page.goto((process.argv[2]??'http://127.0.0.1:5190')+'/#/scenes/campus');
 await page.waitForFunction(()=>!!(window as any).playground?.getState().ready,{},{timeout:90000});
 await page.getByRole('tab',{name:'相机模式',exact:true}).click();
 await page.evaluate(()=>window.__WORLDKIT_EVAL__!.stopLive());
 await page.getByRole('button',{name:'重新绑定预览',exact:true}).click();
 const before=await inspect();
 const rulesDocument={...before.document!,viewSelection:{rules:[{id:'swim-default',when:{state:'swimming'},viewId:'third-person'}]}};
 await page.locator('summary').filter({hasText:/^完整文档/}).click();
 await page.getByRole('textbox',{name:'完整相机文档',exact:true}).fill(JSON.stringify(rulesDocument));
 await page.getByRole('button',{name:'应用草稿',exact:true}).click();
 assert.equal((await inspect()).viewSelection?.suspendedBy,'editing');
 await page.getByRole('button',{name:'恢复自动选择',exact:true}).click();
 assert.equal((await inspect()).viewSelection?.suspendedBy,undefined);
 await page.waitForFunction(()=>!document.querySelector('[aria-label="相机视角选择"]')?.textContent?.includes('编辑草稿中'));

 await page.getByRole('combobox',{name:'相机编辑作用域',exact:true}).click();
 await page.getByRole('option',{name:'项目视图',exact:true}).click();
 await page.locator('summary').filter({hasText:/^朝向$/}).click();
 const target=page.getByRole('combobox',{name:'orientation.recenter.yawTarget 类型',exact:true});
 await target.click();await page.getByRole('option',{name:'world-forward',exact:true}).click();
 await page.getByRole('spinbutton',{name:'orientation.recenter.yawTarget.yawRadians',exact:true}).fill('1');
 await page.getByRole('combobox',{name:'orientation.recenter.enabled',exact:true}).click();await page.getByRole('option',{name:'开启',exact:true}).click();
 for(const name of ['minimumSpeedMetersPerSecond','delaySeconds','yawHalfLifeSeconds'])await page.getByRole('textbox',{name:'orientation.recenter.'+name,exact:true}).fill('0');
 await page.getByRole('button',{name:'应用草稿',exact:true}).click();
 assert.deepEqual((await inspect()).resolved!.values.orientation.recenter.yawTarget,{kind:'world-forward',yawRadians:1});
 await target.scrollIntoViewIfNeeded();await page.screenshot({path:output+'/recenter-controls.png'});
 await page.evaluate(async()=>{await window.__WORLDKIT_EVAL__!.startLive();});
 await page.locator('[data-worldkit-surface]').click({position:{x:250,y:250}});
 await page.keyboard.down('ArrowRight');await page.waitForTimeout(100);await page.keyboard.up('ArrowRight');
 await page.waitForTimeout(300);
 await page.waitForFunction(()=>{const angle=window.__WORLDKIT_EVAL__!.inspectCamera!().intent!.yawRadians-1;return Math.abs(Math.atan2(Math.sin(angle),Math.cos(angle)))<1e-6;});
 await page.locator('summary').filter({hasText:/^相机性能采样$/}).click();
 const profiling=page.getByRole('checkbox',{name:'相机性能采样',exact:true});await profiling.check();
 await page.waitForFunction(()=>window.__WORLDKIT_EVAL__!.inspectCamera!().performance!.stages.fixed!.count>=10);
 await page.getByRole('table',{name:'相机阶段耗时'}).waitFor();await page.getByRole('table',{name:'相机阶段耗时'}).scrollIntoViewIfNeeded();
 await page.screenshot({path:output+'/performance.png'});
 const measured=await inspect();assert(measured.performance!.stages.fixed!.count>0);
 await profiling.uncheck();assert.equal((await inspect()).performance,undefined);
 await page.evaluate(()=>window.__WORLDKIT_EVAL__!.stopLive());
 await page.getByRole('button',{name:'取消应用',exact:true}).click();
 assert.equal((await inspect()).documentHash,before.documentHash);
 assert.equal(await readFile('apps/sdk-playground/config/camera.json','utf8'),original);
 assert.deepEqual(errors,[]);
 await writeFile(output+'/report.json',JSON.stringify({status:'passed',originalHash:before.documentHash,restoredHash:(await inspect()).documentHash,measured:measured.performance,errors},null,2));
 console.log('UI recenter selection / paused apply / live readout / performance toggle / cancel passed');
} catch(error) {await writeFile(output+'/failure.json',JSON.stringify({error:String(error),inspection:await inspect()},null,2));throw error;} finally {await browser.close();}
