export {
  MOUNTED_SKATEBOARD_S1_BOARD_ENTITY_ID,
  MOUNTED_SKATEBOARD_S1_DISMOUNT_ACTION_REF,
  MOUNTED_SKATEBOARD_S1_DISMOUNT_COMMAND_ID,
  MOUNTED_SKATEBOARD_S1_DISMOUNT_REQUEST,
  MOUNTED_SKATEBOARD_S1_DISMOUNT_REQUEST_REF,
  MOUNTED_SKATEBOARD_S1_MOUNT_ACTION_REF,
  MOUNTED_SKATEBOARD_S1_MOUNT_COMMAND_ID,
  MOUNTED_SKATEBOARD_S1_MOUNT_REQUEST,
  MOUNTED_SKATEBOARD_S1_MOUNT_REQUEST_REF,
  MOUNTED_SKATEBOARD_S1_RELATIONSHIP_ID,
  MOUNTED_SKATEBOARD_S1_SCENE_ID,
  augmentMountedSkateboardS1AuthoringSpecV1,
} from "./scenes/mounted-skateboard-s1.js";
